### ISSUE TITLE
Documentation of BLAS and LAPACK functions

### ISSUE THREAD

**Issue by lindahua** [JuliaLang/LinearAlgebra.jl#10]
Documentation of BLAS functions is not completed (for example `trmv` and `trmm` are not there)

Documentation of LAPACK functions seems to be missing.

**Comment by jiahao** [comment]
I made a spreadsheet to track [LAPACK integration in Julia](https://docs.google.com/spreadsheet/pub?key=0Aq8dEVr8KWsHdHJGeXZlLTluX0QzbXVGVThrNWFoZWc&single=true&gid=0&output=html) which may be relevant to the documentation effort.

**Comment by ViralBShah** [comment]
This is a big one, but not a difficult one. Also cc @andreasnoackjensen and @dmbates

**Comment by nutsiepully** [comment]
Is there a way I can help out on this one? Haven't used either package though. Would be happy to learn and document. @ViralBShah - please comment if feasible. Thanks

**Comment by ViralBShah** [comment]
The relevant documentation is in the lapack source in files of the same names add the functions. The main difference is that some of the work arrays are automatically allocated by us. Basically look at the existing lapack documentation and match it with the slightly modified Julia api. See documentation for blas functions as an example as well.

**Comment by nutsiepully** [comment]
Noted. Will follow up and ask if I have any further doubts.

**Comment by timholy** [comment]
Having more documentation here would be awesome. Really excited that you're tackling this.

**Comment by JeffBezanson** [comment]
Is this really going to be done for 0.2? Doesn't seem realistic.

**Comment by nutsiepully** [comment]
@JeffBezanson - i tried giving it some time, but then got busy with other work (school). it was difficult to find documentation for the OpenBLAS functions however. i could only find some descriptions in the fortran [codebase](http://www.netlib.org/blas/)

**Comment by JeffBezanson** [comment]
No worries --- I'm grateful for whatever time you can contribute. My only concern here is managing the 0.2 milestone.

**Comment by nutsiepully** [comment]
I understand, just thought i'd let you know for planning.

**Comment by kshyatt** [comment]
Now that we have LAPACK documentation of some sort I am bumping this. LAPACK functions known to be missing:
- [ ] `laic1`
- [x] `gelqf!{T<:BlasFloat}(A::StridedMatrix{T})`
- [x] `geqlf!{T<:BlasFloat}(A::StridedMatrix{T})`
- [ ] `geqrt!{T<:BlasFloat}(A::StridedMatrix{T}, nb::Integer)`
- [ ] `geqrt3!{T<:BlasFloat}(A::StridedMatrix{T})`
- [x] `geqrf!{T<:BlasFloat}(A::StridedMatrix{T})`
- [x] `gerqf!{T<:BlasFloat}(A::StridedMatrix{T})`
- [x] `geqp3!{T<:BlasFloat}(A::StridedMatrix{T},jpvt::Vector{BlasInt})`
- [x] `geqp3!{T<:BlasFloat}(A::StridedMatrix{T})`
- [x] `stegr!(jobz::Char, dv::Vector, ev::Vector)`
- [ ] `stein!(dv::Vector, ev::Vector, w_in::Vector)`
- [x] `stein!(dv::Vector, ev::Vector, eval::Real)`

**Comment by kshyatt** [comment]
`laic1` is still missing but I think everything else here is covered. Feel free to reopen if that's not the case.
