### ISSUE TITLE
random linalg test failures

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/LinearAlgebra.jl#101]
See, e.g. https://travis-ci.org/JuliaLang/julia/jobs/22428384. I've seen this locally too.

cc: @jiahao, @andreasnoackjensen

**Comment by andreasnoack** [comment]
It looks pretty much like JuliaLang/LinearAlgebra.jl#96

**Comment by StefanKarpinski** [comment]
Ah, I'll close this as a dup then.
