### ISSUE TITLE
`logabsdet` has a weird name

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaLang/LinearAlgebra.jl#1026]
It's not a bug per se, but `logabsdet`'s name makes it sound like it's supposed to return the log-absolute value of the determinant. Would it make sense to create a `log_det_sign` or `log_det_parity` function and then document that it should be preferred to `logabsdet`?

**Comment by stevengj** [comment]
The name seems fine to me.  It does return the log of the absolute value of the determinant; it just returns the sign too if you want it.

SAS [calls it `logabsdet`](https://documentation.sas.com/doc/en/pgmsascdc/v_043/casimllang/casimllang_common_sect221.htm#:~:text=LOGABSDET%20(matrix)%20%3B,procedure%20and%20the%20iml%20action.&text=signifies%20a%20positive%20determinant%2C%20and,element%20for%20the%20logarithm%20value.). Numpy calls it [`slogdet`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.slogdet.html) (but documents one of the return values as `logabsdet`).

It's been around for quite some time in Julia (https://github.com/JuliaLang/LinearAlgebra.jl/issues/13) and hasn't seemed particularly problematic or controversial.     It seems [past the time for bikeshedding](https://discourse.julialang.org/t/psa-julia-is-not-at-that-stage-of-development-anymore/44872) the name.

**Comment by ParadaCarleton** [comment]
> Numpy calls it [`slogdet`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.slogdet.html) (but documents one of the return values as `logabsdet`).

`slogdet` would be a good name too. It follows the rule that function names should say what they do (`sign` and `logdet`).

> SAS [calls it `logabsdet`](https://documentation.sas.com/doc/en/pgmsascdc/v_043/casimllang/casimllang_common_sect221.htm#:~:text=LOGABSDET%20(matrix)%20%3B,procedure%20and%20the%20iml%20action.&text=signifies%20a%20positive%20determinant%2C%20and,element%20for%20the%20logarithm%20value.).

If it's common in other languages that seems fine to me.

> It's been around for quite some time in Julia ([JuliaLang/LinearAlgebra.jl#13](https://github.com/JuliaLang/LinearAlgebra.jl/issues/13)) and hasn't seemed particularly problematic or controversial. It seems [past the time for bikeshedding](https://discourse.julialang.org/t/psa-julia-is-not-at-that-stage-of-development-anymore/44872) the name.

Allowing multiple names is not a breaking change.

**Comment by ararslan** [comment]
> Allowing multiple names is not a breaking change.

...nor is it a good design.

**Comment by oscardssmith** [comment]
We don't seem likely to do this, so closing as not planned.
