### ISSUE TITLE
Access violation in dot product on 32 bit

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/LinearAlgebra.jl#107]
Originally found by @mlubin in https://github.com/JuliaOpt/JuMP.jl/issues/163
Something to do with the fact that one of the vectors is constructed by appending each element?

```
julia> versioninfo()
Julia Version 0.3.0-prerelease+2703
Commit 942ae42* (2014-04-22 18:57 UTC)
Platform Info:
  System: Windows (i686-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY)
  LAPACK: libopenblas
  LIBM: libopenlibm

julia> x = Float64[];
julia> for i=1:5
           push!(x,1.0)
       end
julia> dot(zeros(length(x)),x)
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6a8c090 -- ??? at ???: offset 6a8c090

LAPACKE_ilaver at ???: offset 6a8c090
dot at linalg/blas.jl:99
jl_apply_generic at ???: offset 6ec10cd6
jl_interpret_toplevel_expr at ???: offset 6ec43f12
jl_interpret_toplevel_thunk_with at ???: offset 6ec43270
jl_eval_with_compiler_p at ???: offset 6ec537d7
jl_f_top_eval at ???: offset 6ec16ad0
jl_apply_generic at ???: offset 6ec10cd6
jl_apply_generic at ???: offset 6ec10cd6
jl_f_tupleref at ???: offset 6ec161b7
jl_generate_fptr at ???: offset 6ec1f15c
jl_f_task at ???: offset 6ec4aab8
julia_trampoline at ???: offset 6ec4985c
tgamma at ???: offset 41c028
??? at ???: offset 4013de
BaseThreadInitThunk at ???: offset 7709338a
RtlInitializeExceptionChain at ???: offset 77669f72
RtlInitializeExceptionChain at ???: offset 77669f45
```

Disabling threading in OpenBlas doesn't help.

**Comment by rickhg12hs** [comment]
Same on 32-bit Linux.

**Comment by stevengj** [comment]
Could this be a SIMD alignment thing?   OpenBLAS shouldn't really expect arrays to be 16-byte aligned, but maybe it is missing a check someplace?

**Comment by tkelman** [comment]
Sounds like a decent possibility. Do we have a way of checking array alignment and/or creating an array with specified alignment?

**Comment by JeffBezanson** [comment]
We attempt to allocate all array data with 16-byte alignment.

**Comment by mlubin** [comment]
Including resized arrays?

**Comment by JeffBezanson** [comment]
Looks like the lone exception might be array.c:554.

**Comment by mlubin** [comment]
Does this mean that any vectors obtained from C with `pointer_to_array` are liable to crash Julia when used in LAPACK operations? That seems dangerous.

**Comment by tkelman** [comment]
This is likely a separate issue, but should also be noted: running `julia-debug` only gives the first 2 lines of the backtrace, at least on Windows.

**Comment by vtjnash** [comment]
array.c:554 calls allocb which calls alloc_big, which is aligned, or pool_alloc, which i think is also aligned

**Comment by stevengj** [comment]
OpenBLAS is not supposed to require 16-byte alignment.  My understanding is that it checks the alignment of its arguments and then branches the appropriate code.   However, it is possible that it is missing a check somewhere; if so this is a bug that we should report upstream.

cc: @xianyi

**Comment by JeffBezanson** [comment]
@vtjnash We should find out what sizes are getting allocated; if not a multiple of 16 then `pool_alloc` might not be aligned.

**Comment by JeffBezanson** [comment]
Ah, the problem is that `allocb` offsets the buffer by one word (4 bytes), so doubles are not even 8-byte aligned.

**Comment by stevengj** [comment]
Yikes, you need at least 8-byte alignment.   Not only will OpenBLAS certainly assume 8-byte alignment in its SIMD code (hence the crash), but even scalar code that accesses misaligned data will be horrendously slow.

**Comment by tkelman** [comment]
Confirming this is fixed on 32-bit Windows. Glad you found the culprit!
