### ISSUE TITLE
Difference between dense and sparse matrix (vector) norms

### ISSUE THREAD

**Issue by jumutc** [JuliaLang/LinearAlgebra.jl#112]
Please consider:

```
julia> a = sprand(1,100,0.1)
1x100 sparse matrix with 12 Float64 entries:
    [1  ,   5]  =  0.166406
    [1  ,   7]  =  0.758225
    [1  ,  23]  =  0.242888
    [1  ,  25]  =  0.0558941
    [1  ,  42]  =  0.14784
    [1  ,  46]  =  0.109378
    [1  ,  58]  =  0.554423
    [1  ,  67]  =  0.00975065
    [1  ,  69]  =  0.512135
    [1  ,  71]  =  0.667547
    [1  ,  72]  =  0.0472901
    [1  ,  88]  =  0.226083

julia> norm(a)
3.4978588900522247

julia> norm(full(a))
1.3293854903666515

julia> vecnorm(full(a))
1.3293854903666515

julia> vecnorm(a)
1.3293854903666515
```

**Comment by jumutc** [comment]
The same replicates for matrices as if `a = sprand(100,100,0.1)`

**Comment by jiahao** [comment]
The issue is that `norm` by default computes the L1-norm of a sparse matrix but the L2-norm of a dense matrix. I never quite understood why that would be the design decision (other than us not having a sparse SVD computer which we'd need to compute the L2-norm).

Nevertheless, something is screwy with norm.

``` julia
julia> a=sprand(1,100,0.1); norm(a,1)
3.3686774917241067

julia> norm(a,Inf)
0.87627706242837

julia> norm(full(a),1)
0.87627706242837

julia> norm(full(a),Inf)
3.368677491724107
```

**Comment by jiahao** [comment]
Marking this as a documentation issue for sparse matrices, will open new issue for `norm`.

**Comment by jumutc** [comment]
OK, thanks... I've spent quite some time trying to understand why the same algorithm is working for the dense matrices but not for the sparse ones!

**Comment by StefanKarpinski** [comment]
It seems quite broken that `norm` has different defaults for sparse versus dense.

**Comment by jiahao** [comment]
So I'm going to guess the story here is that everyone normally wants the 2-norm, but we don't yet have sparse svd, so we don't support the 2-norm for sparse matrices. Maybe the right thing to do is set the default to 2 and throw an error to say that only `p=1` or `p=Inf` are supported now?

**Comment by stevengj** [comment]
Throwing an error seems sensible to me.
