### ISSUE TITLE
rank(::SVD) method

### ISSUE THREAD

**Issue by ajinkya-k** [JuliaLang/LinearAlgebra.jl#1126]
Hello! There is no `rank` method for SVD objects. The `rank(::AbstractMatrix)` method already uses an SVD internally, but calling `rank` on an SVD object itself throws an error. I implemented this along with test code and submitting a PR shortly.

**Comment by ajinkya-k** [comment]
Thanks for closing this. Do we need to document this addition in a change log somewhere? Perhaps `NEWS.md`?

**Comment by jishnub** [comment]
That's a good point. With the separation of the repos, I'm unsure how the NEWS.md updates will work. Perhaps @KristofferC might be able to suggest the right approach.

**Comment by ajinkya-k** [comment]
Thanks. Do we need to reopen this issue?

**Comment by jishnub** [comment]
I don't think we need to reopen the issue. The news entry may be added separately once we figure out the steps.
