### ISSUE TITLE
Update to OpenBLAS 0.2.9

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/LinearAlgebra.jl#116]
Some serious issues were discovered in OpenBLAS. We should ideally wait for 0.2.9, or pick something from the develop branch.

https://github.com/xianyi/OpenBLAS/commit/10a16bd690a5e6a2b6198cc448e4940b112af565#commitcomment-6442973

https://github.com/xianyi/OpenBLAS/wiki/Fixed-optimized-kernels-To-do-List

Cc: @andreasnoackjensen @staticfloat

**Comment by lindahua** [comment]
What is the problem using v0.2.9-rc2 ?  The issue JuliaLang/LinearAlgebra.jl#114 was serious enough to justify switching to a newer version, even if it is not formally released.

**Comment by ViralBShah** [comment]
I don't think it has all the fixes. Maybe an rc3.

**Comment by andreasnoack** [comment]
rc2 does not include a fix of inverse on Windows for some architectures so I think we'll need a new release. There was also a big fix merge last week which we probably want to have as well.

**Comment by vtjnash** [comment]
updating openblas will fix JuliaLang/julia#6710

**Comment by JeffBezanson** [comment]
Just leaving a note here to remind us to revert the GEMV workaround when openblas is updated.

**Comment by stevengj** [comment]
whoops, put the wrong issue number in a commit.

**Comment by vtjnash** [comment]
Aw, You got me all excited.

**Comment by ViralBShah** [comment]
To be on the safe side, until OpenBLAS 0.2.9 is released, we may want to build LAPACK from source, rather than the patched version that OpenBLAS includes.

**Comment by vtjnash** [comment]
Openblas 0.2.9 appears to have been released.

**Comment by lindahua** [comment]
Yes, here is the link to the release notes: https://github.com/xianyi/OpenBLAS/releases

**Comment by stevengj** [comment]
Can this issue be closed now?

**Comment by Keno** [comment]
Yes, I believe so.
