### ISSUE TITLE
diag inconsistent behavior

### ISSUE THREAD

**Issue by davidlizeng** [JuliaLang/LinearAlgebra.jl#120]
Hi,
This comes up in both Julia 0.2.1 and 0.3.0-prerelease+3544. When I do something like

```
A = [1 2; 3 4]
diag(A, 2)
```

I get a bounds error, as expected. But if i do

```
diag(A, -2)
```

I get a 0 element array. Is this expected behavior of diag? Shouldn't both be giving bounds errors?

Thanks!

**Comment by fxbrain** [comment]
numpy gives in both cases a zero element array back, which seems to be more consistent to me.

your latter case e.g. yields the somewhat strange StepRange object 3:3:2, which is indeed zero element, but looks rather strange to me.
