### ISSUE TITLE
No sparse `det`

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/LinearAlgebra.jl#124]
``` julia
julia> B = sprand(100,100,0.2);

julia> det(B);
ERROR: `det` has no method matching det(::SparseMatrixCSC{Float64,Int64})
```

I'm not so familiar with sparse linear algebra, but we could use `lufact` for this as well. Unfortunately the same trick doesn't work for `logdet`: is there any way to get this from UMFPACK?

cc: @andreasnoackjensen

**Comment by toivoh** [comment]
Why would the LU decomposition work less well for `logdet` than for `det`?
Instead of taking the product of the diagonal elements of L (if U has ones on the diagonal), you would take the sum of their logarithms. (In both cases accounting for the sign of the permutation in P.)

**Comment by andreasnoack** [comment]
I think that the `det` and `logdet` methods in `linalg/dense.jl` can be defined for `AbstractMatrix` which would solve this issue. It appears that the change provokes some unrelated ambiguity warnings, but I think I can fix them soon.

**Comment by simonbyrne** [comment]
@toivoh I just meant that there is no `logdet` method for `SparseMatrixCSC` types, and from what I can tell, UMFPACK doesn't have a method that we can easily wrap, so we might need to write our own.

**Comment by ViralBShah** [comment]
We are able to extract the `L` and `U` from UMFPACK though. That should make it possible to do something quick.

**Comment by toivoh** [comment]
Ok, I see.
