### ISSUE TITLE
Error in single threaded positive definite inverse in OpenBLAS

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/LinearAlgebra.jl#126]
As reported at the [list](https://groups.google.com/forum/#!topic/julia-users/LXu76Ayj0Yw)

Issue filed: https://github.com/xianyi/OpenBLAS/issues/410

**Comment by ViralBShah** [comment]
We need to have this fix in 0.3, and it seems likely that the fix will be part of openblas `0.2.10`.

Cc: @xianyi @wernsaar

**Comment by tkelman** [comment]
the linalg tests are already really long, but could any additional tests have caught the difference between single and multi threaded openblas here?

**Comment by andreasnoack** [comment]
I think, it only happened for large matrices, so we can just set `n=1000` instead of `n=10`:smiley:

**Comment by mlubin** [comment]
It seems like the linalg tests are becoming mostly a unit test suite for OpenBLAS.

**Comment by tkelman** [comment]
Yeah, largely. Their own tests are more comprehensive than ours, but Julia gets installed on a wider variety of machines than the OpenBLAS devs have access to.

**Comment by ViralBShah** [comment]
Maybe we should have a small set of tests that are run with different problem sizes and with different numbers of threads.

**Comment by tkelman** [comment]
[OpenBLAS 0.2.10 is out](https://github.com/xianyi/OpenBLAS/releases) with the fix for this, time for another bump?

**Comment by ViralBShah** [comment]
Could you test it out and bump it? I am just boarding a flight to India and will be mostly in an aluminium tube for the next 30 hours or so.

**Comment by tkelman** [comment]
Hm, judging by https://github.com/xianyi/OpenBLAS/issues/415 there may be trouble on 32 bit Linux?

**Comment by ViralBShah** [comment]
Looks like it has been fixed and there is a new 0.2.10 tag.

**Comment by staticfloat** [comment]
I'm currently testing out 0.2.10 on Ubuntu and OSX.  I will submit a PR when I've finished.

**Comment by ViralBShah** [comment]
@staticfloat Did this work out?

**Comment by staticfloat** [comment]
Through my adventures, we've gotten a re-tagged 0.2.10 (along with a promise from the devs that they'll try to just release new versions instead of retagging).  PR is [here](https://github.com/JuliaLang/julia/pull/7659), but it would be nice if someone could verify that the issue reported in this thread is actually solved by version bump.

**Comment by ViralBShah** [comment]
I just merged it, thinking from the comments in the PR that it was good to go. Anyways, I am building right now and will speak up if it fails.

**Comment by tkelman** [comment]
I reproduced this problem in a pre-0.2.10 version and saw it fixed in the first tagged version of 0.2.10, which differed only in a single line from the second tag, so I think we're okay

**Comment by ViralBShah** [comment]
I don't see the PosDef exception any more.

**Comment by ViralBShah** [comment]
I wonder if we can print a line in the banner encouraging everyone who downloads julia to run the tests during the RC stage and report issues.

**Comment by tkelman** [comment]
Why just during the RC stage? Should put it on the download page. Julia is under heavy development, here's how to run the test suite first thing after installing a binary, if it doesn't pass then search github for similar issues and add a comment if you see something that's already been reported, or open a new issue if you can't find anything similar.

**Comment by ViralBShah** [comment]
That is a valid point, and I actually like the idea. The downloads page can have detailed instructions, and the banner can have something just as a reminder. Perhaps the request to run tests can be made quiet after the tests are run for that particular version.

**Comment by ivarne** [comment]
Maybe a `not tested`/`tested`/`test failure` notice in yellow/green/red?

**Comment by ViralBShah** [comment]
Great idea! Perhaps we should have a new issue for this.
