### ISSUE TITLE
Error in LAPACK.gelsy!

### ISSUE THREAD

**Issue by timholy** [JuliaLang/LinearAlgebra.jl#134]
`gelsy!` is for solving least-squares problesm. http://www.netlib.org/lapack/lapack-3.1.1/html/dgelsy.f.html says that it can handle rank-deficient matrices, but I'm seeing something different:

``` julia
A = float([0 1;
           0 2;
           0 3])
b = float([2,4,6])

julia> A\b
2-element Array{Float64,1}:
 0.0
 2.0

julia> solution, rank = Base.LAPACK.gelsy!(A,b)
([0.0,0.0],0)
```

I'm guessing this is their problem and not ours, but I thought I'd check with @andreasnoackjensen first.

@andreasnoackjensen, FYI I'm interested in `gelsy!` for performance reasons. I'll file this as a separate issue.

**Comment by timholy** [comment]
For reference, our own code has the same problem if `pivot=false`. What puzzles me is that `gelsy` explicitly uses pivoting.

**Comment by andreasnoack** [comment]
Hm. This is weird.

```
julia> A=[0 1;0 2;0 3.];b=[2,4,6.];
julia> LAPACK.gelsy!(A,b)
([0.0,0.0],0)

julia> A=[0 1;0 2;0 3.];b=[2,4,6.];
julia> LAPACK.gelsy!(A,b)
([0.0,0.0],0)

julia> A=[0 1;0 2;0 3.];b=[2,4,6];
julia> LAPACK.gelsy!(A,b)
([0.0,2.0],1)

julia> A=[0 1;0 2;0 3.];b=[2,4,6.];
julia> LAPACK.gelsy!(A,b)
([0.0,0.0],0)
```

I'll look into this, but need some breakfast and coffee first.

**Comment by andreasnoack** [comment]
I'm not sure about your pivot comment. `xgelsy` uses pivoted QR. That is necessary for handling the rank deficient case.

**Comment by timholy** [comment]
Sorry, I was pretty vague. Maybe this will help:

```
julia> A = float([0 1;
                  0 2;
                  0 3])
3x2 Array{Float64,2}:
 0.0  1.0
 0.0  2.0
 0.0  3.0

julia> F = qrfact(A, pivot=false)
QRCompactWY{Float64}(3x2 Array{Float64,2}:
 0.0   1.0     
 0.0  -3.60555 
 0.0   0.535184,2x2 Triangular{Float64,Array{Float64,2},:U,false}:
 0.0  0.0   
 0.0  1.5547)

julia> b = float([2,4,6])
3-element Array{Float64,1}:
 2.0
 4.0
 6.0

julia> F\b
2-element Array{Float64,1}:
 0.0
 0.0

julia> F = qrfact(A, pivot=true)
QRPivoted{Float64}(3x2 Array{Float64,2}:
 -3.74166   0.0
  0.421793  0.0                                                                                                                                          
  0.63269   0.0,[1.26726,0.0],[2,1])                                                                                                                     

julia> F\b
2-element Array{Float64,1}:                                                                                                                              
 0.0
 2.0
```

So the puzzle is that while our code works if we use pivoting, `gelsy` supposedly uses pivoting yet doesn't work.

I think the fact that `rank` comes back as 0 explains a lot of the trouble. The section about `Q1` in the doc link above would suggest that this outcome is a predictable consequence of having RANK=0. Note that SVD is aware that this matrix has rank 1, not 0.
