### ISSUE TITLE
choleskey decomposition returns wrong type

### ISSUE THREAD

**Issue by tomhaber** [JuliaLang/LinearAlgebra.jl#138]
The chol method seems to return a Triangular of a Triangular of a Matrix

julia> L = chol(varCov)
14x14 Triangular{Float64,Triangular{Float64,Array{Float64,2},:U,false},:U,false}:

line 82 in cholesky.jl is the culprit
chol(A::AbstractMatrix, uplo::Symbol=:U) = Triangular(chol!(copy(A), uplo), uplo, false)
and should probably say 
chol(A::AbstractMatrix, uplo::Symbol=:U) = chol!(copy(A), uplo)

I'm using julia 0.4

Kind regards,
Tom

**Comment by andreasnoack** [comment]
Thanks!
