### ISSUE TITLE
documentation for eigfact()[:vectors]

### ISSUE THREAD

**Issue by mlubin** [JuliaLang/LinearAlgebra.jl#140]
According to the documentation, you can access the eigenvectors of a matrix `A` as `eigfact(A)[:vectors]`, so I went and tried `eigfact(A)[:vectors][1]` expecting to get the vector corresponding to the first eigenvalue, but instead got a scalar, the first element of a matrix which contains the eigenvectors on the columns(?). This seems a bit misleading and possibly unjulian, though I understand why you wouldn't want to return a `Vector{Vector}}` for efficiency reasons. Anyway could use better documentation.

@andreasnoack

**Comment by jiahao** [comment]
You've probably figured this out by now, but `A=eigfact(A)[:vectors]` returns a matrix `A` where each column is an eigenvector. `A[1]` invokes the linear indexing rule which (conceptually) flattens `A` into a vector, and then takes its first element. So `A[1]` is the first entry of the first eigenvector. To get the first eigenvector, you would want the slice `A[:,1]` or its equivalent array view.

Agreed, better documentation could help here.

**Comment by mlubin** [comment]
Thanks @jiahao!
