### ISSUE TITLE
blkdiag should be blkdiagm to be consistent with diag vs diagm

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/LinearAlgebra.jl#146]
To be consistent with the difference between diag and diagm, it seems that blkdiag should be renamed blkdiagm.

**Comment by tkelman** [comment]
Well, not unless someone can come up with a nice "getter" API for block-diagonals. `blkdiag` still only applies to sparse, so considering the merging of JuliaLang/julia#7600 it would actually make more sense to just deprecate the sparse-only `blkdiag` and use the current implementation for `cat([1, 2], sparsematrices...)`. cc @Jutho

**Comment by pao** [comment]
Either that, or add the dense `blkdiag()` as a shorthand for that `cat` call.

**Comment by Jutho** [comment]
It might be that the behaviour of `cat` is changed to the preference of @JeffBezanson , i.e. where it allows to an arbitrary number of blocks in several directions. I don't have time to try to implement this right now, but wouldn't mind if `cat` is changed in that way, and the generalization I have currently given it be made available under some other name. and then `blkdiag` could indeed be made such that is calls (or is a special case) of this.

**Comment by ViralBShah** [comment]
This is now renamed to `blockdiag`. We are unlikely to change this name for 1.0 now.
