### ISSUE TITLE
Illegal hardware instruction when performing inner products

### ISSUE THREAD

**Issue by jameskyle** [JuliaLang/LinearAlgebra.jl#150]
I can reliable crash julia with an illegal instruction error using the following:

```
julia> v1 = [1;-1;0;1;1]; v2 = [3;-3;2;5;5]; v3 = [5;1;3;2;8];
julia> (v2 .* v1) / (v1 .* v1)
[1]    69731 illegal hardware instruction  julia
```

**Comment by ihnorton** [comment]
`versioninfo(true)`?

**Comment by ViralBShah** [comment]
On 0.3.3 and master, both, I get:

```
julia> v1 = [1;-1;0;1;1]; v2 = [3;-3;2;5;5]; v3 = [5;1;3;2;8];

julia> (v2 .* v1) / (v1 .* v1)
ERROR: DimensionMismatch("matrix is not square")
 in chksquare at linalg.jl:170
 in Triangular at linalg/triangular.jl:6 (repeats 2 times)
 in A_ldiv_B! at linalg/factorization.jl:386
 in \ at linalg/factorization.jl:481
 in \ at linalg/dense.jl:417
 in / at linalg/generic.jl:236
```

**Comment by jameskyle** [comment]
Ah, sorry, this is 0.3.2. Let me upgrade.

**Comment by jameskyle** [comment]
Full versioning for 0.3.3 and crash:

versioninfo(true)
Julia Version 0.3.3
Commit b24213b\* (2014-11-23 20:19 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.0.0)
  CPU: Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
  WORD_SIZE: 64
  uname: Darwin 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64 i386
Memory: 16.0 GB (3457.93359375 MB free)
Uptime: 131848.0 sec
Load Avg:  2.31982421875  1.9013671875  1.5751953125
Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz:
       speed         user         nice          sys         idle          irq
JuliaLang/julia#1  2700 MHz      36275 s          0 s      56819 s     564531 s          0 s
JuliaLang/julia#2  2700 MHz       1580 s          0 s       1790 s     654231 s          0 s
JuliaLang/julia#3  2700 MHz      28877 s          0 s      25912 s     602812 s          0 s
JuliaLang/julia#4  2700 MHz       1602 s          0 s       1843 s     654156 s          0 s
JuliaLang/julia#5  2700 MHz      26337 s          0 s      22960 s     608304 s          0 s
JuliaLang/julia#6  2700 MHz       1610 s          0 s       1863 s     654128 s          0 s
JuliaLang/julia#7  2700 MHz      25478 s          0 s      22306 s     609817 s          0 s
JuliaLang/julia#8  2700 MHz       1623 s          0 s       1891 s     654086 s          0 s

  BLAS: libopenblas (NO_AFFINITY HASWELL)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Environment:
  CFLAGS = -Qunused-arguments
  CPPFLAGS = -Qunused-arguments
  GOPATH = /Users/jkyle/Projects/Go
  HOME = /Users/jkyle
  PATH = /usr/local/bin:/usr/local/sbin:/Users/jkyle/Projects/Go/bin:/Users/jkyle/bin:/usr/bin:/bin:/usr/sbin:/sbin
  TERM = screen-256color
  WORKON_HOME = /Users/jkyle/.virtualenvs
  XPC_FLAGS = 0x0
  JULIA_SHELL = /usr/local/bin/zsh
Package Directory: /Users/jkyle/.julia/v0.3
1 required packages:
- Jewel                         0.9.0
  11 additional packages:
- Color                         0.3.12
- Compat                        0.2.0
- Compose                       0.3.9
- DataStructures                0.3.5
- FactCheck                     0.2.1
- FixedPointNumbers             0.0.4
- Iterators                     0.1.7
- JSON                          0.3.9
- JuliaParser                   0.5.3
- LNR                           0.0.1
- Lazy                          0.5.0

julia> v1 = [1;-1;0;1;1]; v2 = [3;-3;2;5;5]; v3 = [5;1;3;2;8];

julia> (v2 .\* v1) / (v1 .\* v1)

signal (4): Illegal instruction: 4

signal (4): Illegal instruction: 4

signal (4): Illegal instruction: 4

signal (4): Illegal instruction: 4
.L1_47 at /usr/local/opt/openblas-julia/lib/libopenblas.dylib (unknown line)
.L1_47 at /usr/local/opt/openblas-julia/lib/libopenblas.dylib (unknown line)
.L1_47 at /usr/local/opt/openblas-julia/lib/libopenblas.dylib (unknown line)
[1]    82217 illegal hardware instruction  julia

**Comment by tkelman** [comment]
Sounds like https://github.com/staticfloat/homebrew-julia/issues/130#issuecomment-64034199 ?

**Comment by jameskyle** [comment]
Recompiling according to static float/homebrew-julia#130 instructions.

**Comment by jameskyle** [comment]
All fixed!

Thanks!
