### ISSUE TITLE
Error:  copmputing eigen on BigFloat

### ISSUE THREAD

**Issue by paulanalyst** [JuliaLang/LinearAlgebra.jl#1507]
A=rand(100,100)

R = convert (Matrix {BigFloat}, cor (A))

m,v=eig(R)

ERROR: no method eigfact!(Array{Any,1}, Array{BigFloat,2})
 in eigfact at linalg/factorization.jl:669
 in eig at linalg/factorization.jl:673

**Comment by pao** [comment]
Much of the linear algebra stuff isn't fully generalized to BigFloat types. This is being tracked in issue JuliaLang/LinearAlgebra.jl#11. Thanks!
