### ISSUE TITLE
eig and eigvals don't agree in the last ulp

### ISSUE THREAD

**Issue by alanedelman** [JuliaLang/LinearAlgebra.jl#1508]
Not sure if this matters but just surprised that these are not exactly
equal.  Anyone care to comment how this happens? (just for fun)

```
S=[1/(i+j) for i=1:3,j=1:3];eig(S)[1] - eigvals(S)

3-element Array{Float64,1}:
 -1.79978e-17
 -2.77556e-17
 -1.11022e-15
```

**Comment by stevengj** [comment]
Alan, isn't LAPACK using QR when you request only eigenvalues, and D&C when you request eigenvalues and eigenvectors?  Hence I wouldn't expect them to agree to an ulp.

**Comment by alanedelman** [comment]
That would do it.

**Comment by andreasnoack** [comment]
I little more detail on this. The symmetric solvers in julia use `xsyevr` from LAPACK and, as @stevengj suggests, a solver is chosen for the tridiagonal problem depending on if the vectors are requested or not. When only the values are requested, they are calculated from the square root free QR algorithm in `xsterf`. However, when the vectors are requested, it is not the D&C algorithm `xstedc`but the more recent RRR based algorithm `xstemr` that is chosen.

**Comment by alanedelman** [comment]
i looked in lapack and there are versions that avoid sqrt's 
i wonder if that is still needed

**Comment by andreasnoack** [comment]
I can see that the reference in the manual is LAWN17 from 1989 so some development could have happened. However, on my Mac there is a big difference. For a n=10000 problem, the version with square root (dsteqr) takes 3.34 seconds and without (dsterf) takes 12.47. On julia.mit.edu the difference is not as big: 4.43 vs. 5.51.

**Comment by jiahao** [comment]
I couldn't find a particular reference to this, but it is true that computing sqrts (and invsqrts) have gotten enormously faster over my computing lifetime. Computer gaming isn't entirely frivolous after all.
