### ISSUE TITLE
eigvals not defined for integer matrices

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/LinearAlgebra.jl#1509]
Even though `eig` is.

(I feel like I've reported this issue before, but I can't find it.   Maybe it's just _deja vu_ since I keep running into problems where functions are defined for floating-point matrices but there is no promotion rule for integer matrices.)

**Comment by ViralBShah** [comment]
This does feel like a deja vu. I recollect @andreasnoackjensen having done something about this.

**Comment by jiahao** [comment]
Possibly JuliaLang/LinearAlgebra.jl#20?

**Comment by andreasnoack** [comment]
Fixed by JuliaLang/julia#4738. I thought this one had been fixed, but it was only so for generalized eigenvalues and singular values. Generalized singular values also did not work for integer matrices.
