### ISSUE TITLE
symmetric tridiagonal eigenvalues performance

### ISSUE THREAD

**Issue by alanedelman** [JuliaLang/LinearAlgebra.jl#1511]
How is this possible?  There is a tridiagonal eigensolver inside
every dense sym eigensolver?
don't tell me i'm getting unwanted eigenvectors too or something ....

a sanity check is that for n large -- doubling n would take 
8 x the time for the dense method,  and perhaps 4 x the time
for the tridiagonal method, when compared to the original n.

More importantly, the tridiagonal should be strictly less time
than the dense as the tridiagonal is inside the dense.
At least that's the theory

``` julia
julia> n=1000;a=randn(n,n);s=a+a'; @time eigvals(s);
elapsed time: 0.357638326 seconds

julia> n=1000;a=randn(n,n);s=a+a';d=diag(s);e=diag(s,1); @time eigvals(SymTridiagonal(d,e));
elapsed time: 0.766760059 seconds
```

I see that `@time eig` is a bit more reasonable but somehow i doubt this is `dsteqr` time.

**Comment by andreasnoack** [comment]
Different solvers. Right now `eigvals(SymTridiagonal)` calls `dstebz`, but `eigvals(Hermitian)` calls `dsyevr` that uses `dstemr` for solving the tridiagonal problem. We don't have `dstemr` wrapped yet but a fast hack shows that it is much faster. At least when the absolute tolerance in `stebz` is small. I get

``` julia
julia> min([@elapsed LinAlg.LAPACK.stebz!('A', 'E', 0.0, 0.0, 0, 0, -1.0, d, e)[1] for i = 1:10])
0.538316322

julia> min([@elapsed LinAlg.LAPACK.stebz!('A', 'E', 0.0, 0.0, 0, 0, .00001, d, e)[1] for i = 1:10])
0.130601928

julia> min([@elapsed stemr!('N', 'A', copy(d), copy(e), 0.0, 0.0, 0, 0, true)[1] for i = 1:10])
0.063476249

julia> norm(stemr!('N', 'A', copy(d), copy(e), 0.0, 0.0, 0, 0, true)[1] - LinAlg.LAPACK.stebz!('A', 'E', 0.0, 0.0, 0, 0, -1.0, d, e)[1])
7.194901430589435e-13
```

**Comment by alanedelman** [comment]
it's hard to keep it all straight but
dstebz is the tried and true qr algorithm   while
dstemr may do bisection, or may do dqds it seems

now that it's easy to compare, we should see how all do in terms of time and accuracy for
the smallest in absolute value of the eigenvalues

I find the following comparative timings amazingly unbelievable:
is qr really wasting a ton of time??????
and yet that's what we teach students about how eigenvalues are computed
are we just lying these days

``` julia
julia> d=randn(n); e=randn(n-1); T=SymTridiagonal(d,e); B=Bidiagonal(d,e,true);

julia> @time(eig(T));
elapsed time: 28.410723801 seconds

julia> @time(svdvals(B));
elapsed time: 2.39826233 seconds
```

**Comment by andreasnoack** [comment]
According to

http://www.netlib.org/lapack/lug/node48.html

`dstebz` does bisection. `dsterf` is the QR algorithm and it is wrapped in the `stev!` function. By the way, I found out that `dstegr` is just a wrapper of `dstemr` and hence already wrapped as the Julia function `stegr!`. Maybe things are not so strange:

QR:

``` julia
julia> min([@elapsed LinAlg.LAPACK.stev!('N', copy(d), copy(e))[1] for i = 1:10])
0.038312104
```

RRR(dstemr/dstegr):

``` julia
julia> min([@elapsed LinAlg.LAPACK.stegr!('N', 'A', copy(d), copy(e), 0.0, 0.0, 0, 0, 1e-12)[1] for i = 1:10])
0.059268677
```

Bisection:

``` julia
julia> min([@elapsed LinAlg.LAPACK.stebz!('A', 'E', 0.0, 0.0, 0, 0, -1., d, e)[1] for i = 1:10])
0.535571912
```

Maybe it is not a good idea to default to use `dstebz`.

**Comment by alanedelman** [comment]
good for tracking this down

some terminology
i don't think rrr is the name of the algorithm, but rather the relatively robust representation inside the algorithm
when eigenvalues get close
the algorithm itself is trying to be dqds, but falls back to bisection when it feels it needs to for accuracy

seems like dstebz is indeed a non-contender

would be good if we could maybe have stev! the default with the dstemr/dstegr somehow available
and perhaps somehow make the choice easy enough that even I can remember it, and i'm intimately
familiar with all the algorithms :-) but this alphabet soup is a nightmare

**Comment by andreasnoack** [comment]
In the pull request the timings make more sense.

``` julia
julia> min([@elapsed eigvals(s) for i = 1:10])
0.278785754

julia> min([@elapsed eigvals(SymTridiagonal(d,e)) for i = 1:10])
0.039498983
```

**Comment by alanedelman** [comment]
Yay! Thank you.

**Comment by andreasnoack** [comment]
The changes in JuliaLang/julia#3280 also affects the functions `eigmax` and `eigmin`. It seems like bisection (dstebz) is slightly faster for these calculations relative to the hybrid(dstegr/stemr). 

``` julia
julia> n=100000;d=randn(n);e=randn(n-1);

julia> min([@elapsed eigmax(SymTridiagonal(d,e)) for i = 1:10])
0.076593384

julia> min([@elapsed LinAlg.LAPACK.stebz!('I','E',0.0,0.0,length(d),length(d),-1.0,d,e) for i = 1:10])
0.063364488
```

Should we use bisection for these calculations?

**Comment by alanedelman** [comment]
I could imagine bisection is a good choice for a targeted eigenvalue

**Comment by kbarros** [comment]
Coming across this a decade later, it looks like the LinearAlgebra module is in good shape, and automatically calls the right LAPACK functions as appropriate. Here is how to run updated benchmarks:

```jl
using LinearAlgebra
n = 5000
d=randn(n); e=randn(n-1); T=SymTridiagonal(d,e);

# Eigenvalues only
@time(eigvals(T)); # 0.3 s, calls LAPACK.stev!
@time LAPACK.stegr!('N', 'A', copy(d), copy(e), 0.0, 0.0, 0, 0); # 0.5 s
@time LAPACK.stebz!('A', 'E', 0.0, 0.0, 0, 0, 1e-5, d, e); # 1.4 s

# Eigenvalues and eigenvectors
@time(eigen(T)); # 2.1 s
@time LAPACK.stegr!('V', 'A', copy(d), copy(e), 0.0, 0.0, 0, 0); # 2.1s
```

~~Curiously, I couldn't find a Julia LAPACK wrapper to [`sstemr`](https://netlib.org/lapack/explore-html-3.4.2/dc/d9d/sstemr_8f.html), an $O(N^2)$ algorithm based on RRRs, Relatively Robust Representations. The Netlib docs don't say much about the difference between `sstemr` and [`sstegr`](https://netlib.org/lapack/explore-html-3.4.2/d6/d0e/sstegr_8f.html), which is the one used in [`LinearAlgebra/src/tridiag.jl`](https://github.com/JuliaLang/julia/blob/c31710a7d93c84b0e1f79c7d9c7ba7bca948ba10/stdlib/LinearAlgebra/src/tridiag.jl#L274).~~

**Update** The call graph on the Netlib page indicates that `sstegr` calls to `sstemr`, so I guess it makes sense to always call `sstegr`.
