### ISSUE TITLE
Return types inference in linalg 

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/LinearAlgebra.jl#1512]
This has been discussed under other issues but to keep track of it I post an issue on it.

Several of the functions in linalg_dense.jl and Lapack.jl have their return type depended on input argument values. I don't think it would be difficult to fix but will take some time to ensure get through all the functions without breaking anything.

**Comment by JeffBezanson** [comment]
Hey, might as well take advantage of dynamic typing some times!

**Comment by ViralBShah** [comment]
There are cases that return a or (a, b), depending on the input. Wouldn't that mess up type inference?

**Comment by JeffBezanson** [comment]
It doesn't mess up type inference, it just leads to the inferred type being...more complex. But the most important thing is to have a nice interface. I'd only fix this if the result is non-ugly to use.

**Comment by ViralBShah** [comment]
Great.

**Comment by andreasnoack** [comment]
I agree. What about the complex thing? Julia has

``` julia
julia> sqrt(1)
1.0

julia> sqrt(-1)
NaN
```

but

``` julia
julia> eig([1 2; 4 3])
([-1.0, 5.0],
2x2 Float64 Array:
 -0.707107  -0.447214
  0.707107  -0.894427)

julia> eig([1 2; -4 3])
([2.0+2.64575im, 2.0-2.64575im],
2x2 Complex128 Array:
 0.204124-0.540062im  0.204124+0.540062im
      0.816497+0.0im       0.816497+0.0im)
```

Okay or a problem?

**Comment by JeffBezanson** [comment]
The main reason for this is that the performance of scalar sqrt is just too important.
Aside from that, it depends how people prefer to think about eig. If you generally know whether to expect real eigenvalues, it might make sense to have a separate function.

**Comment by andreasnoack** [comment]
Okay. Thank you for the clarification.
