### ISSUE TITLE
Implement expm

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/LinearAlgebra.jl#1515]
People have asked for expm on a number of occasions. The following implementation contributed for scilab can serve as a guide for the julia implementation.

http://www.scilab.org/contrib/index_contrib.php?page=displayContribution&fileID=1231
http://www.scilab.org/contrib/download.php?fileID=1231&attachFileName=expm.sci

It is likely that we will run into some un-implemented linear algebra functions, but that should just help completeness.

**Comment by JeffBezanson** [comment]
An M language implementation can be found at http://www.maths.uq.edu.au/expokit/matlab/. There is also code there for computing `expm(A)*v` without forming the intermediate matrix.

**Comment by pao** [comment]
Quoting @asbidyarthy in JuliaLang/LinearAlgebra.jl#1514:

``` Julia
# We used the formula for expm in julia,

# Compute all eigenvectors and eigenvalues
(d,V)= eig(A)
D=diagm(d)
expm(A)= V * diagm(exp(diag(D)) / V;
```

It gives the correct answer for symmetric A in julia.
It does not work for asymmetric A in julia
(gives no method for / Array{Complex128,2},Array{Complex128,2} in base.jl:60)
-- the same however works in matlab.

The function is about 4.45 times slower than matlab library expm
for 100x100 matrices and 2.9 times slower than matlab library
expm for 1000x1000 matrices.

**Comment by dmbates** [comment]
The problem @asbidyarthy mentions with the speed will be related to using the eigenvalue-eigenvector decomposition.  That is the most versatile but also one of the slowest ways of computing the matrix exponential.  The famous paper on "Nineteen Dubious Ways to Compute the Exponential of a Matrix" (www.cs.cornell.edu/cv/researchpdf/19ways+.pdf) gives alternatives.  Generally the Pade approximation is used.  See, e.g. unsupported/Eigen/src/MatrixFunctions/MatrixExponential.h in the Eigen sources.

**Comment by StefanKarpinski** [comment]
More issues (also posted on JuliaLang/LinearAlgebra.jl#1514):
1. Doing `D = diagm(d)` then `diag(D)` is a lot of pointless work — you could just write `diagm(exp(d))`.
2. Isn't the formula `V*diagm(exp(d))/V` incorrect? I'm pretty sure the right formula is `V*diagm(exp(d))*V'` — which is also much faster (especially because we don't actually take the transpose at all in this case).

You could write this latter formula even more efficiently as

``` julia
diagmm(V,exp(d))*V'
```

But yes, a better built-in `expm` implementation is definitely called for so that people can just use it and know it will be both accurate and fast.

**Comment by dmbates** [comment]
I see that in the Matrix package for R we grabbed the C code for the Pade approximation from octave.  I think most of it could be written in Julia with calls to various Lapack functions.  It would make for a good illustration of scalar computation speed in Julia.

``` c


const static double padec [] = /* for matrix exponential calculation. */
{
  5.0000000000000000e-1,
  1.1666666666666667e-1,
  1.6666666666666667e-2,
  1.6025641025641026e-3,
  1.0683760683760684e-4,
  4.8562548562548563e-6,
  1.3875013875013875e-7,
  1.9270852604185938e-9,
};

/**
 * Matrix exponential - based on the _corrected_ code for Octave's expm function.
 *
 * @param x real square matrix to exponentiate
 *
 * @return matrix exponential of x
 */
SEXP dgeMatrix_exp(SEXP x)
{
    const double one = 1.0, zero = 0.0;
    const int i1 = 1;
    int *Dims = INTEGER(GET_SLOT(x, Matrix_DimSym));
    const int n = Dims[1], nsqr = n * n, np1 = n + 1;

    SEXP val = PROTECT(duplicate(x));
    int i, ilo, ilos, ihi, ihis, j, sqpow;
    int *pivot = Calloc(n, int);
    double *dpp = Calloc(nsqr, double), /* denominator power Pade' */
    *npp = Calloc(nsqr, double), /* numerator power Pade' */
    *perm = Calloc(n, double),
    *scale = Calloc(n, double),
    *v = REAL(GET_SLOT(val, Matrix_xSym)),
    *work = Calloc(nsqr, double), inf_norm, m1_j/*= (-1)^j */, trshift;
    R_CheckStack();

    if (n < 1 || Dims[0] != n)
    error(_("Matrix exponential requires square, non-null matrix"));
    if(n == 1) {
    v[0] = exp(v[0]);
    UNPROTECT(1);
    return val;
    }

    /* Preconditioning 1.  Shift diagonal by average diagonal if positive. */
    trshift = 0;        /* determine average diagonal element */
    for (i = 0; i < n; i++) trshift += v[i * np1];
    trshift /= n;
    if (trshift > 0.) {     /* shift diagonal by -trshift */
    for (i = 0; i < n; i++) v[i * np1] -= trshift;
    }

    /* Preconditioning 2. Balancing with dgebal. */
    F77_CALL(dgebal)("P", &n, v, &n, &ilo, &ihi, perm, &j);
    if (j) error(_("dgeMatrix_exp: LAPACK routine dgebal returned %d"), j);
    F77_CALL(dgebal)("S", &n, v, &n, &ilos, &ihis, scale, &j);
    if (j) error(_("dgeMatrix_exp: LAPACK routine dgebal returned %d"), j);

    /* Preconditioning 3. Scaling according to infinity norm */
    inf_norm = F77_CALL(dlange)("I", &n, &n, v, &n, work);
    sqpow = (inf_norm > 0) ? (int) (1 + log(inf_norm)/log(2.)) : 0;
    if (sqpow < 0) sqpow = 0;
    if (sqpow > 0) {
    double scale_factor = 1.0;
    for (i = 0; i < sqpow; i++) scale_factor *= 2.;
    for (i = 0; i < nsqr; i++) v[i] /= scale_factor;
    }

    /* Pade' approximation. Powers v^8, v^7, ..., v^1 */
    AZERO(npp, nsqr);
    AZERO(dpp, nsqr);
    m1_j = -1;
    for (j = 7; j >=0; j--) {
    double mult = padec[j];
    /* npp = m * npp + padec[j] *m */
    F77_CALL(dgemm)("N", "N", &n, &n, &n, &one, v, &n, npp, &n,
            &zero, work, &n);
    for (i = 0; i < nsqr; i++) npp[i] = work[i] + mult * v[i];
    /* dpp = m * dpp + (m1_j * padec[j]) * m */
    mult *= m1_j;
    F77_CALL(dgemm)("N", "N", &n, &n, &n, &one, v, &n, dpp, &n,
            &zero, work, &n);
    for (i = 0; i < nsqr; i++) dpp[i] = work[i] + mult * v[i];
    m1_j *= -1;
    }
    /* Zero power */
    for (i = 0; i < nsqr; i++) dpp[i] *= -1.;
    for (j = 0; j < n; j++) {
    npp[j * np1] += 1.;
    dpp[j * np1] += 1.;
    }

    /* Pade' approximation is solve(dpp, npp) */
    F77_CALL(dgetrf)(&n, &n, dpp, &n, pivot, &j);
    if (j) error(_("dgeMatrix_exp: dgetrf returned error code %d"), j);
    F77_CALL(dgetrs)("N", &n, &n, dpp, &n, pivot, npp, &n, &j);
    if (j) error(_("dgeMatrix_exp: dgetrs returned error code %d"), j);
    Memcpy(v, npp, nsqr);

    /* Now undo all of the preconditioning */
    /* Preconditioning 3: square the result for every power of 2 */
    while (sqpow--) {
    F77_CALL(dgemm)("N", "N", &n, &n, &n, &one, v, &n, v, &n,
            &zero, work, &n);
    Memcpy(v, work, nsqr);
    }
    /* Preconditioning 2: apply inverse scaling */
    for (j = 0; j < n; j++)
    for (i = 0; i < n; i++)
        v[i + j * n] *= scale[i]/scale[j];


    /* 2 b) Inverse permutation  (if not the identity permutation) */
    if (ilo != 1 || ihi != n) {
    /* Martin Maechler's code */

#define SWAP_ROW(I,J) F77_CALL(dswap)(&n, &v[(I)], &n, &v[(J)], &n)

#define SWAP_COL(I,J) F77_CALL(dswap)(&n, &v[(I)*n], &i1, &v[(J)*n], &i1)

#define RE_PERMUTE(I)               \
    int p_I = (int) (perm[I]) - 1;      \
    SWAP_COL(I, p_I);           \
    SWAP_ROW(I, p_I)

    /* reversion of "leading permutations" : in reverse order */
    for (i = (ilo - 1) - 1; i >= 0; i--) {
        RE_PERMUTE(i);
    }

    /* reversion of "trailing permutations" : applied in forward order */
    for (i = (ihi + 1) - 1; i < n; i++) {
        RE_PERMUTE(i);
    }
    }

    /* Preconditioning 1: Trace normalization */
    if (trshift > 0.) {
    double mult = exp(trshift);
    for (i = 0; i < nsqr; i++) v[i] *= mult;
    }

    /* Clean up */
    Free(work); Free(scale); Free(perm); Free(npp); Free(dpp); Free(pivot);
    UNPROTECT(1);
    return val;
}
```

**Comment by ViralBShah** [comment]
@dmbates Could you also provide the complex version? I'll try my hand at converting it all to julia.

**Comment by dmbates** [comment]
I don't think we handled the complex version in the Matrix package for R.  I'll see if there is anything in the expm package for R or in the Octave sources.

**Comment by dmbates** [comment]
I have an implementation of expm using the algorithm from Higham, 2008, Functions of Matrices, Theory and Computation, SIAM.

I wrote it as a module to gain experience with the module system but creating a module for a single function is a bit of overkill, I imagine.  Rather than check these files in to the source tree, I created https://gist.github.com/3417277.  Should this code go into base/linalg_lapack.jl or some other place?

**Comment by ViralBShah** [comment]
linalg_lapack.jl sounds like the right place for now. 

I would like to refactor the lapack code (yet again), so that we create an LAPACK module, where all the LAPACK wrappers live (say, lapack.jl), and then have a linalg.jl that just all the linear algebra stuff that calls LAPACK and BLAS functions as necessary. Does that sound ok?

**Comment by StefanKarpinski** [comment]
> I would like to refactor the lapack code (yet again), so that we create an LAPACK module, where all the LAPACK wrappers live (say, lapack.jl), and then have a linalg.jl that just all the linear algebra stuff that calls LAPACK and BLAS functions as necessary. Does that sound ok?

Yes, that's a good idea. It's a little trickier to do than one would expect, but go for it.

**Comment by ViralBShah** [comment]
Implemented in commit b409daa01ee98d1f447d59b3b9bc27325aba3bd9

**Comment by dmbates** [comment]
A recent blog entry from the Mathworks, http://blogs.mathworks.com/cleve/2012/07/23/a-balancing-act-for-the-matrix-exponential/?s_eid=PSM_2096, has a reference to further work by a student of Nicholas Higham.

**Comment by StefanKarpinski** [comment]
Fascinating read. Nick Higham's [matrix function toolbox](http://www.ma.man.ac.uk/~higham/mftoolbox) could provide inspiration for similar Julia functions. It is, however, GPLv3, so we'd have to be careful to either preserve that license on a straight port or only rely on Higham's code for inspiration to our own implementations.

**Comment by zhuangh** [comment]
Sorry to jump in this old post. I am curious about this topic. For the Cleve's blog mentioned by @dmbates, I test expm in Julia, it generates the correct answer. Is the implementation of expm in Julia using "balancing the exponential", which is expm(A) = V*diagm(exp(d))/V, where (d, V) = eig(A).

**Comment by jiahao** [comment]
Perhaps @ViralBShah would know better, but the implementation of `expm` [here](https://github.com/JuliaLang/julia/blob/a327b47bbfb6d49006a88d439f469e00ab9403f1/base/linalg/dense.jl#L209) appears to be Algorithm 10.20, which uses Padé approximants in the scale-and-square method as described in Higham, 2008 ([doi:10.1137/1.9780898717778.ch10](http://epubs.siam.org/doi/abs/10.1137/1.9780898717778.ch10)).

**Comment by ViralBShah** [comment]
That's right - and I think it was @dmbates who did that implementation, IIRC.

**Comment by zhuangh** [comment]
@ViralBShah @jiahao  thanks, I test that case in matlab 2013, it generates the wrong results, which means matlab hasn't implement expm in the same way as julia (Highman 2008).
