### ISSUE TITLE
promote integer types for LAPACK routines

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/LinearAlgebra.jl#1517]
@HomerReid wrote:

> eig() fails for integer matrices:
> 
> ```
>  julia> eig([1 2; 2 1])
>  no method eig(Array{Int32,2},)
>  in method_missing, boot.j:250
>  in run_repl, /home/homer/hacking/julia/j/client.j:23
>  in _start, /home/homer/hacking/julia/j/client.j:153
> ```

The solution is to add promotions for Real types in the lapack macros.

**Comment by ViralBShah** [comment]
But, we'd have to change each BLAS/LAPACK/ARPACK macro and such. Isn't there a simpler way?

**Comment by StefanKarpinski** [comment]
See the discussion in JuliaLang/julia#133.

**Comment by ViralBShah** [comment]
Let's say we have a promotion rule from Array{Int32} to Array{Float32}, and foo(Array{Float32}). 

If I now call foo(Array{Int32}), will julia automatically do the promotion and then call foo on the promoted value?

**Comment by StefanKarpinski** [comment]
No, that's not how our promotions work. Promotions are only for combinations of operands; things like `+(Int64, Float64)`, in which situation both operands get converted to the smallest common supertype — in this case, `Float64`. For "promoting" array arguments, we would just define the following method:

```
foo{T<:Real}(x::Array{T}) = foo(float(x))
```

That's it. That method will get called for any real-valued array that doesn't have a specific implementation already defined, and first convert `x` to an array of floats (assuming proper vectorization of the `float` function, which isn't there yet, but should be), and then calls the core `foo` implementation for floats on it.
