### ISSUE TITLE
Sparse \ not implemented for multiple RHS and for integer inputs

### ISSUE THREAD

**Issue by abhijithch** [JuliaLang/LinearAlgebra.jl#20]
While trying to solve for Ax=b, where A is sparse, i get an error as follows;

´´´
julia> A_s=sparse(A)
4x4 sparse matrix with 16 Int64 nonzeros:
    [1, 1]  =  1
    [2, 1]  =  2
    [3, 1]  =  7
    [4, 1]  =  1
    [1, 2]  =  2
    [2, 2]  =  3
    [3, 2]  =  6
    ⋮
    [1, 3]  =  3
    [2, 3]  =  4
    [3, 3]  =  3
    [4, 3]  =  7
    [1, 4]  =  4
    [2, 4]  =  5
    [3, 4]  =  6
    [4, 4]  =  5

julia> xx=A_s\y
ERROR: no method (SparseMatrixCSC{Int64,Int64},Array{Int64,2})
´´´
# Here y is 4x2. But i tried it after..

´´´
julia> yy=[1 2 3 4]
1x4 Int64 Array:
 1  2  3  4
´´´

get the same error,
´´´
julia> xxx=A_s\yy
ERROR: no method (SparseMatrixCSC{Int64,Int64},Array{Int64,2})
´´´
checking the type of the sparse matrix,
´´´
julia> typeof(A_s)
SparseMatrixCSC{Int64,Int64} 
´´´
converted the int64 matrix to float64 it worked. So the conclusion is the \ will not work for more than one RHS in Ax=b problem.

**Comment by stevengj** [comment]
A lot of the linear-algebra functions don't work on integer matrices.

(Of course, they invariably require floating-point internally, but in some cases we have automatic promotion.)

**Comment by ViralBShah** [comment]
We also need to deal with multiple RHS, which we do in the dense case:

```
julia> s = speye(5) \ ones(5,2)
ERROR: no method \(SparseMatrixCSC{Float64,Int64},Array{Float64,2})
```

**Comment by ViralBShah** [comment]
Cc: @dmbates

**Comment by jiahao** [comment]
I believe this is fixed now? (cc: @ViralBShah)

**Comment by ViralBShah** [comment]
```
julia> s = speye(Int32, 5) \ ones(Int32,5,2)
5x2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
```
