### ISSUE TITLE
occasional SingularException in arpack test

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/LinearAlgebra.jl#23]
For example here: https://travis-ci.org/JuliaLang/julia/jobs/11222298

Can the test be made more reliable?

**Comment by jtravs** [comment]
Is this caused by the issue @stevengj mentioned at: https://github.com/JuliaLang/julia/pull/4164#issuecomment-23430890

In general we need much better test problems and testing for eigs in shift mode. That was why I was against merging just yet as discussed in: JuliaLang/julia#4164

**Comment by ViralBShah** [comment]
I did mean to disable the tests for now, as I have yet to investigate the case that @stevengj talked about. Doing so now.

**Comment by ViralBShah** [comment]
commit 8a200cb6d045919fdfe01a0ddeb23db01137a0ef

**Comment by ViralBShah** [comment]
@jtravs I merged it to nudge more work in this direction. We are really close to getting full `eigs` and `svds` functionality.

**Comment by ViralBShah** [comment]
Haven't seen this for a while. Let's reopen if still an issue.
