### ISSUE TITLE
norm(Float64[0,NaN]) == 0

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/LinearAlgebra.jl#236]
`norm(Float64[0,NaN]) == norm(Float64[0,NaN],2) == norm(Float64[0,NaN],Inf) == 0`, whereas I would expect NaN in this case.  The L1 norm gives NaN.

Seems to affect both Julia 0.3 and 0.4-dev.

**Comment by stevengj** [comment]
The basic problem is that `max(0.0, NaN) == 0`, when it should probably give NaN?  Actually, the way `max` is written, it looks like this was somewhat intentional?? See JuliaLang/julia#10736.

@lbenet and @timholy, can you comment on the desired semantics of `max` here?

**Comment by StefanKarpinski** [comment]
I would strongly encourage making `max` and `min` over `NaN` produce `NaN`.

**Comment by simonster** [comment]
See also JuliaLang/julia#7866

**Comment by StefanKarpinski** [comment]
In fact, this very example is a pretty strong argument for why it should be `NaN` rather than `0.0`.

**Comment by lbenet** [comment]
@stevengj Indeed, in JuliaLang/julia#10736 `max(0.0, NaN) == 0` was intentionally coded to mimic the results obtained in v0.3.
(I think this discussion is continuing in JuliaLang/julia#7866).
