### ISSUE TITLE
Should mutating LAPACK functions receive all the arguments they return?

### ISSUE THREAD

**Issue by dmbates** [JuliaLang/LinearAlgebra.jl#24]
@andreasnoackjensen @ViralBShah Currently LAPACK functions such as `geqrt3!` return two matrices but take only one matrix as an argument.  It makes sense in that the value of the function only depends on the rectangular matrix `A` but it means that you can't update a QR object in place.  The triangular matrix `T` in the QR object will always be freshly allocated.  The cost is negligible until you work with very large matrices in some kind of an iterative method.

To me the best approach would be to introduce a new `geqrt3!` methods that takes both `vs` and `T` as arguments and a second that takes only `A`.  I can create a pull request with this change and similar changes for the other flavors if this approach seems reasonable.

**Comment by ViralBShah** [comment]
This is certainly desirable. Please go for it.

**Comment by andreasnoack** [comment]
I have had some of the same considerations, but actually I thought about saving all the allocated arrays (including workspace) of the LAPACK subroutine in the factorization object. Then we could have two versions of the LAPACK wrapper, one that takes all necessary arrays as input and only checks that the dimensions of the arrays are right and one version with fever input that allocates the necessary arrays and returns all the allocated arrays. It would make it possible to update factorizations without new array allocations and it wouldn't break any functionality of the factorization.

**Comment by dmbates** [comment]
@andreasnoackjensen That's an interesting idea.  I am just testing a version with the changes that I suggested now.  If no problems show up I will create a pull request and perhaps you can look at it to see if you want to implement that change.  Alternatively we could wait until the dust has settled from the 0.2 release.  I imagine we could become very unpopular if something crept in that delayed 0.2

**Comment by andreasnoack** [comment]
@dmbates I think your suggestion is the right way to go forward. I'll do some experiments locally but postpone changes until after 0.2.

**Comment by ViralBShah** [comment]
This change seems small enough that we can consider it for 0.2, IMO.

**Comment by StefanKarpinski** [comment]
If it's non-breaking and low risk, it's fine for 0.2.

**Comment by jiahao** [comment]
bump. Marking as `0.2.x`.

**Comment by ViralBShah** [comment]
JuliaLang/julia#4268 is merged now.
