### ISSUE TITLE
Documentation for A_ldiv_B!

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/LinearAlgebra.jl#254]
Documentation for `A_ldiv_B!` and company is missing. 
Is it correct that it does in-place replacement of `A` by `A / B` ?  If so, I'll add docs for these functions.

**Comment by KristofferC** [comment]
Not always. See JuliaLang/LinearAlgebra.jl#201.

**Comment by dpsanders** [comment]
OK, thanks. What do you suggest? See also https://github.com/JuliaLang/LinearAlgebra.jl/issues/216

**Comment by jakebolewski** [comment]
I feel an incomplete stub is better than no documentation at all.  All of this can be incrementally improved over time.

**Comment by kshyatt** [comment]
Since JuliaLang/LinearAlgebra.jl#201 was resolved, can someone add docs for this now?

**Comment by stevengj** [comment]
Done in JuliaLang/julia#16702
