### ISSUE TITLE
svds implementation

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/LinearAlgebra.jl#28]
It seems that the way octave implements `svds` is as follows:

```
(V, s) = eigs ([spzeros(m,m), b; b', spzeros(n,n)], b_k, b_sigma, b_opts);
```

If you have the octave repo, you can see the implementation in `octave-3.6.4/scripts/sparse/svds.m`. 
I see some pre and post processing too.

Should we go ahead this way for our `svds` implementation too?

**Comment by jiahao** [comment]
I'm pretty sure this trick uses the relationship between singular values as "square roots" of the eigenvalues, and as such would be numerically unstable in that the computation works with a matrix that has a condition number which is roughly squared compared to the original matrix. (In the same vein as why normal equation methods like CGNE aren't currently favored in iterative methods)

Given that `IterativeSolvers.jl` now offers the Golub-Kahan-Lanczos method for computing singular values via [`svdvals_gkl()`](https://github.com/JuliaLang/IterativeSolvers.jl/blob/master/src/lanczos.jl#L37), I think we should close this and work on providing the full SVD factorization (i.e. return the singular vectors also) from `IterativeSolvers`.

**Comment by ViralBShah** [comment]
Agree.

**Comment by ViralBShah** [comment]
On second thoughts, it would be nice to have a working `svds` implementation, which could be replaced later.

**Comment by ViralBShah** [comment]
Related: JuliaLang/LinearAlgebra.jl#106
