### ISSUE TITLE
support smallest/largest algebraic eigenvalues in eigs

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/LinearAlgebra.jl#30]
The `eigs` function, according to its documentation, only supports computation of the smallest or largest magnitude eigenvalues.  But ARPACK also supports `"LA"` and `"SA"` settings to find the smallest or largest algebraic eigenvalues, for Hermitian matrices.

If this isn't supported, what do we need to do to support it?  If it is supported somehow, we should document it.

**Comment by ViralBShah** [comment]
This should be easy to support. I am at MIT oct 23-28. It would be good to do an arpack sprint then and complete eigs and svds then. Many of these things are just incomplete because nobody had asked for them so far.

**Comment by acroy** [comment]
Seems that the current `eigs` already supports `"LA"` and `"SA"` for real symmetric matrices:

```
julia> eigs([[-1.  1]; [1 1]],which="LA",nev=1)
([1.4142135623730951],
2x1 Array{Float64,2}:
 0.382683
 0.92388 ,

1,1,2,[0.0,0.0])

julia> eigs([[-1.  1]; [1 1]],which="SA",nev=1)
([-1.4142135623730947],
2x1 Array{Float64,2}:
 -0.92388 
  0.382683,

1,1,2,[0.0,0.0])
```

Hermitian matrices are not correctly identified (adding `|| ishermitian(A)` [here](https://github.com/JuliaLang/julia/blob/master/base/linalg/arnoldi.jl#L12) should do it), which prevents using `"LR"`, `"SR"` etc.

Once JuliaLang/julia#5776 is settled, I will fix the documentation. A separate issue is probably the error handling. Either we make sure that only valid input is passed to ARPACK or we generate more detailed descriptions in `ARPACKException` or both.

**Comment by jiahao** [comment]
Currently, we only wrap the real symmetric kernels (`s/dsaupd`, `s/dseupd`) and the real and complex nonsymmetric kernels (`s/d/z/cnaupd`, `s/d/z/cneupd`) from ARPACK, so the only way to compute with Hermitian matrices is to use the general complex nonsymmetric kernels. If anyone feel strongly about wrapping other ARPACK kernels, feel free to open a new PR. Otherwise I'm going ahead to wrap up this PR.

**Comment by jiahao** [comment]
Everything else should be subsumed by JuliaLang/julia#5776
