### ISSUE TITLE
Running additional local processes affects behavior of inv()

### ISSUE THREAD

**Issue by sbos** [JuliaLang/LinearAlgebra.jl#31]
The following code prints different numbers depending on were the "-p N" option passed to Julia interpreter or not.

``` julia
function bug(N)
    A = zeros(N, N) 

    for i=1:N 
        A[i, i] = 1. 
        for j=i-1:-1:1 
            if i-j < 6 
                A[i, j] = -exp( (j-i) / 3. ) 
            end 
        end 
        A[i, i-1:-1:1] /= -(sum(A[i, i-1:-1:1]) - 0.5) 
    end 

    return sum(inv(A) .< 0)
end

for N=1:110
    println(N, " ", bug(N))
end
```

On my machine "-p 1" causes non-zero negative counts starting from N=65. What is especially funny is that even "-p 0" reproduces this bug (?).

My version of Julia is:

```
Julia Version 0.2.0-prerelease+3986
Commit 2e5242a* 2013-10-09 23:17:29 UTC
Platform Info:
  System: Darwin (x86_64-apple-darwin11.4.2)
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT NO_AFFINITY)
  LAPACK: libopenblas
  LIBM: libopenlibm
```

CPU is Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz, Mac OS 10.7.5. Julia was installed from homebrew.

Discussion in the mailing list: https://groups.google.com/forum/#!topic/julia-users/zT9cVrWQ5t4

**Comment by andreasnoack** [comment]
I don't get the wrong result. I am on

```
Julia Version 0.2.0-prerelease+4014
Commit 59256c2* 2013-10-12 05:19:52 UTC
Platform Info:
  System: Darwin (x86_64-apple-darwin12.5.0)
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY)
  LAPACK: libopenblas
  LIBM: libopenlibm
```

Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz

**Comment by bartolsthoorn** [comment]
I'm also unable to reproduce this, not getting negative counts.

```
Version 0.2.0-prerelease+4014
Commit 59256c2 2013-10-12 05:19:52 UTC
x86_64-apple-darwin12.5.0
```

With Intel Core 2 Duo @ 2.53 GHz

**Comment by kmsquire** [comment]
From the mailing list discussion, Elliot was able to reproduce this on a Core i5 Mac mini.

cc: @staticfloat

**Comment by JeffBezanson** [comment]
I imagine this is related to calling `disable_threaded_libs`?

**Comment by sbos** [comment]
Hm, what is disable_threaded_libs? I could try to disable it and see if this helps

**Comment by JeffBezanson** [comment]
We call that when multiple processes are in use. see multi.jl:923

**Comment by jiahao** [comment]
bump

is this still lurking around in post-0.2?

**Comment by staticfloat** [comment]
I can confirm this is still present in a5e8e5a, although I'm having a hard time tracking down exactly where this is happening.  I tried to create a smaller testcase assuming that perhaps `inv()` was the culprit, and although I do get two different answers depending on whether or not I use `Base.disable_threaded_libs()` or not, the magnitude of the error (although surprisingly high) isn't as large as I thought it would be:

```
N = 80
A = randn(N,N)
B = inv(A)
Base.disable_threaded_libs()
C = inv(A)
```

Trying to compare the two a bit:

```
julia> maximum(abs(B - C))
1.0918483894784003e-9

julia> sum(abs(B - C))
5.554758456816078e-7

julia> eps()
2.220446049250313e-16
```

Linear algebra gurus:  Is this indicative of anything more interesting than just a change in algorithm?  I'm assuming that disabling threading in openblas, etc. is just causing it to switch to a different algorithm and thus converge to a slightly different answer, but I have no concrete evidence of that.

**Comment by jiahao** [comment]
I was unable to reproduce this on my i5 system.

`inv` in this case first computes the LU decomposition, which in turn dispatches to `LAPACK.getrf!`, and second computes the inverse from the result of the LU decomposition. Could you try `B=LU(A); Base.disable_threaded_libs(); C = LU(A); norm(B.factors-C.factors)` and see if the problem lies in the first step.

**Comment by staticfloat** [comment]
@jiahao The factors do not differ:

```
julia> N = 80                                                                   
80

julia> A = randn(N,N);

julia> B = LU(A);

julia> Base.disable_threaded_libs()

julia> C = LU(A);

julia> norm(B.factors - C.factors)
0.0
```

Although the `ipiv` vector differs.  Not sure if that's significant:

```
julia> B.ipiv
80-element Array{Int32,1}:
 67
 59
 66
 77
  6
 11
 41
 50
 80
  ⋮
 73
 76
 78
 80
 77
 80
 80
 80
 80

julia> C.ipiv
80-element Array{Int32,1}:
  1
  2
  3
  4
  5
  6
 41
  8
  9
  ⋮
 77
 73
 74
 77
 76
 79
 78
 79
 80
```

**Comment by jiahao** [comment]
There is something very weird going on with `B.ipiv`. the pivot vector `ipiv` should be a permutation of `[1:80]` which indicates the order in which the rows (I think) are swapped during the LU process. I don't understand why there should be multiple `80`s in it.

**Comment by jiahao** [comment]
cc: @andreasnoack

**Comment by dmbates** [comment]
The `ipiv` vector is not a permutation, although you can create a permutation from it.

**Comment by dmbates** [comment]
See the code for `getindex(A::LU,d::Symbol)` in `base/linalg/factorization.jl` for the method of creating the permutation vector, `p`, from the `ipiv` vector.

**Comment by jiahao** [comment]
Thanks for the correction @dmbates. Should the parallel and serial codes be expected to return different sequences of pivots? Wouldn't that change the actual pivoted LU factorization, or is this already accounted for in `.factors`?

**Comment by JeffBezanson** [comment]
I believe openblas includes a special parallel LU, and it certainly makes sense to me to do different pivoting in parallel. If openblas only parallelized BLAS operations I'd guess this difference wouldn't happen (EDIT: or rather, the difference would be much less)

In my opinion, for data that fits in memory compromising on pivoting for bit more parallelism isn't worth it.

**Comment by dmbates** [comment]
@jiahao For different `ipiv` vectors you would expect to get different `factors` matrices.  The `factors` matrix and the `ipiv` vector are direct results of `LAPACK.getrf!` and must be used together to reconstruct the original matrix.

It may be that the structure of this particular matrix is such that the pivots are indeterminate and different pivot sequences will result in the same factors.

**Comment by andreasnoack** [comment]
@staticfloat Do you still have the machine on which this happened and are you still able to reproduce it?

**Comment by staticfloat** [comment]
On my macbook pro, running the 0.3.10 (homebrew) binaries, I'm able to synthesize a case that is about as bad as the one shown above:

```
begin
    srand(41)
    N = 80
    A = randn(N,N)
    B = inv(A)
    Base.disable_threaded_libs()
    C = inv(A)

    println("Infinity norm of difference: $(maximum(abs(B - C)))")
    println("L-1 norm of difference: $(sum(abs(B - C)))")
end
```

Running the above yields:

```
Infinity norm of difference: 1.3468479664879851e-9
L-1 norm of difference: 6.526577266130484e-7
```

Here's my `versioninfo()`:

```
julia> versioninfo()
Julia Version 0.3.10
Commit c8ceeef* (2015-06-24 13:54 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.3.0)
  CPU: Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

Running on the 0.3.10 (Homebrew) binaries on my Mac Mini, I get similar results:

```
Infinity norm of difference: 1.3468479664879851e-9
L-1 norm of difference: 6.526577266130484e-7

julia> versioninfo()
Julia Version 0.3.10
Commit c8ceeef* (2015-06-24 13:54 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.3.0)
  CPU: Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

Running on the 0.3.10 Ubuntu binaries, I also get similar results:

```
Infinity norm of difference: 2.3602524379384704e-9
L-1 norm of difference: 1.1441235184808315e-6

julia> versioninfo()
Julia Version 0.3.10
Commit c8ceeef (2015-06-24 13:54 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7 CPU         960  @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by andreasnoack** [comment]
@staticfloat Would you try the original test again to see if that is still an issue? I don't think the errors you show are larger than can be justified by theory and if I compare to an inverse computed in `BigFloat`s they are similar.

**Comment by staticfloat** [comment]
I can no longer reproduce the original bug on 0.4.1.  Yay!  @sbos, I'm going to close this, if you still run into the issue feel free to comment here and we can continue the discussion.

**Comment by sbos** [comment]
Yes, it seems that bug is fixed now.
