### ISSUE TITLE
Fat QR: A≠QR

### ISSUE THREAD

**Issue by alanedelman** [JuliaLang/LinearAlgebra.jl#32]
Bravo for using thin QR's and thin SVDs as defaults.
(though not the subject of this issue)

If a user happens to type qr(A,false) on a tall skinny matrix,
the returned R is square, rather than the shape of A.

For example

```
(q,r)=qr(randn(6,3), false)
```

returns a 6x6 matrix times a 3x3 matrix which are not compatible for matmul

PROS:  less memory  
CONS:  A is not QR, though A is Q[:,1:3]*R

just wasn't sure if this was deliberate or not -- if deliberate, perhaps put into the doc
if not , perhaps fix

**Comment by ViralBShah** [comment]
Cc: @andreasnoackjensen @dmbates

**Comment by andreasnoack** [comment]
I don't think we should return the tall `R`. When you want the fat `Q` it is not because you want to multiply it with `R`. My preferred solution is deprecate all the MATLAB compatible version and only continue with the factorizations. With the latter this would not come up as an issue, but for now we better just document how it works.

**Comment by dmbates** [comment]
I agree with @andreasnoackjensen

**Comment by alanedelman** [comment]
Then document it is.  Thanks eveyrone.

**Comment by alanedelman** [comment]
While we are on the subject, what about qr(A) when m< n ???  (or qrfact?)

Current behavior: 

```
 DimensionMismatch("Matrix cannot have less rows than columns")
```

Recommended behavior?

```
  Think of A as [ Asquare Arest ]
  [Q,R]=qr(Asquare)
  Return Q  and  [R Q'*Arest]
```

**Comment by ViralBShah** [comment]
Also, we can use our cool packed QRPackedQ transposed multiplication!

**Comment by ViralBShah** [comment]
It seems that @alanedelman 's suggestion only makes sense for the matlab style interface, and not the factorization interface.

**Comment by alanedelman** [comment]
> > It seems that @alanedelman 's suggestion only makes sense for the matlab style interface, and not the >>factorization interface.

   I think it may just make sense for the factorization interface as well.  The use case would be to
compute Q and apply Q' to other arrays.  This is fairly common, independent of the m,n relation.

**Comment by andreasnoack** [comment]
@alanedelman JuliaLang/julia#4565 does what you suggest.

**Comment by ViralBShah** [comment]
I was playing around with JuliaLang/julia#4565 to write some tests, and realized that `\` needs to be updated as well.

```
julia> afat = rand(3,6)
3x6 Array{Float64,2}:
 0.781856  0.980857  0.9763    0.376826   0.315377  0.916733
 0.524703  0.976472  0.162143  0.739671   0.557227  0.254567
 0.911267  0.198476  0.234486  0.0578524  0.615929  0.609922

# This one uses QRP
julia> afat \ ones(3)
6-element Array{Float64,1}:
  0.561618 
  0.214107 
 -0.0937543
  0.219228 
  0.530986 
  0.209819 

# Need to update the definition of \ for the m < n case 
julia> qrfact(afat) \ ones(3)
ERROR: BoundsError()
 in copy! at array.jl:49
 in getindex at array.jl:296
 in \ at linalg/factorization.jl:320
```

**Comment by ViralBShah** [comment]
@andreasnoackjensen I am not sure of the best way to do this.  The `R` is no longer triangular in the fat case. Should this also be done in the same way you did it for QRP, following `xgelsy`?

**Comment by andreasnoack** [comment]
I think the best solution is to give an error that suggests the pivoted version. I don't think you want to solve the system without pivoting.

**Comment by ViralBShah** [comment]
Is there a reason for having the non-pivoted implementation at all? What if `qr` was pivoted and we get rid of `qrp`?

**Comment by andreasnoack** [comment]
I guess it is best to have access to both. E.g., if you only want to use `Q` then I think you are fine without the pivoting. There is also a efficiency consideration
julia> A=randn(10000,100);

julia> @time qrpfact(A);
elapsed time: 0.264657371 seconds (8029592 bytes allocated)

julia> @time qrfact(A);
elapsed time: 0.074457789 seconds (8080264 bytes allocated)

```
```

**Comment by ViralBShah** [comment]
How about we just keep `qr` with a `pivoted={true,false}` optional argument? Perhaps the default option can the safe one.

**Comment by alanedelman** [comment]
I agree.  Most of the time I don't care or prefer the pivoted version but on rare occasions I don't want pivoting
so the option is nice
