### ISSUE TITLE
Woodbury and Bunch Kaufman

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/LinearAlgebra.jl#33]
I wonder if we should move the Woodbury and Bunch Kaufman out of Base into a LinearAlgebra.jl package. There all kinds of other stuff that could potentially be in there, like all the stuff from Golub and Van Loan.

**Comment by JeffBezanson** [comment]
Let's just leave them in Base unless they are truly not useful.

**Comment by jiahao** [comment]
In JuliaLang/julia#2593, @dmbates wrote:

> the description of the \ operator is inaccurate. The Hermitian case uses the BunchKaufman factorization, not the Cholesky factor.

Things have probably changed a lot in the intervening months, but I cannot find any evidence that the `BunchKaufman` factorization is being used in the linear solver polyalgorithm anymore. In fact, I can't find a single use of `BunchKaufman` anywhere in the base library other than the `bkfact` and `bkfact!` functions which compute and return the factorization.

You can still use `BunchKaufman` factorizations in linear solvers (via `A_ldiv_B!`) and compute matrix inverses, but that's pretty much it. These functions wrap `LAPACK.sytrs!` and `LAPACK.hetrs!`.

**Comment by jiahao** [comment]
Similarly, `Woodbury` is entirely self-contained and essentially not referenced outside of `base/linalg/woodbury.jl`.

**Comment by timholy** [comment]
It's used in Grid, but there's no reason we can't have Grid load a package.

**Comment by jiahao** [comment]
Apologies, `BunchKaufman` is indeed used in the linear solver exactly as @dmbates wrote. `\` on `Symmetric` and `Hermitian` matrices call `bkfact`.

**Comment by jakebolewski** [comment]
Woodbury has been extracted (#10024), BunchKaufman is more useful to have in Base.
