### ISSUE TITLE
QRPackedQ should DimensionMismatch rather than give wrong numbers

### ISSUE THREAD

**Issue by Keno** [JuliaLang/LinearAlgebra.jl#34]
Reported by @alanedelman:

```
Q=qrfact(randn(3,3))[:Q]
Q*eye(4) 
```

   DimensionMismatch("")  
as expected,  but the below is just wrong

```
eye(4)*Q
 4x4 Array{Float64,2};
-0.276925  -0.702638  -2.19207  -0.68322 
 0.945082  -0.322394  -1.02281  -0.796033
 0.173588  -2.5497    -2.49979  -1.776   
 0.480913  -1.03707   -1.0433    0.337647 
```

**Comment by alanedelman** [comment]
One extra comment:

I also noticed that 

Q=qrfact(randn(3,3))[:Q]

works for

Q_eye(3)  and
Q_eye(6)

and no other values.

It's not completely crazy either despite the knee jerk reaction   as the Q can represent
the 6x3 matrix or the 6x6 matrix as it has the same information content

**Comment by ViralBShah** [comment]
Cc: @andreasnoackjensen

**Comment by andreasnoack** [comment]
I had accidentally commented out the dimension check when I changed the QR subroutine. This is fixed in the pull request.
