### ISSUE TITLE
Proposal: Better linear algebra benchmarks

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/LinearAlgebra.jl#35]
Continuing from the discussion in JuliaLang/julia#4651 with @staticfloat:
- [ ] The benchmarks currently report everything relative to the C timings. This is useful for many of the reported tests, but less so for the linear algebra benchmarks. For these tests, it is customary to report effective FLOPS, e.g.
  - [NCSA BLAS Performance Comparison](http://www.ncsa.illinois.edu/UserInfo/Perf/BLAS/) (2003)
    ![DGEMM benchmark](http://www.ncsa.illinois.edu/UserInfo/Perf/BLAS/img/ia64_2-dgemm.png)
  - [nVidia CUBLAS](https://developer.nvidia.com/cublas) (2011)
    ![CUBLAS batched GEMM](https://developer.nvidia.com/sites/default/files/akamai/cuda/images/CUDALibs/cublas_41_matrix.jpg)
  
  We should probably report our linear algebra benchmarks in effective FLOPS.
- [ ] Benchmarks results should be rendered nicely using Julia and packages such as [Gadfly](https://github.com/dcjones/Gadfly.jl). (@StefanKarpinski)

**Comment by staticfloat** [comment]
I think these are neat, and can be orthogonal to codespeed reporting (for now); these are the kind of graphs we would put on julialang.org bragging about how `0.2.0` is so great, rather than automatically creating these in codespeed.

**Comment by blakejohnson** [comment]
@jiahao see JuliaLang/julia#3566 for some comments about the benchmark design. I mainly just threw something out there that was reasonable enough to get started with. I do think FLOPS is a fine unit for reporting the numbers.

As far as picking a number of repetitions, there is a natural tension between accuracy of the results, and the amount of time it takes to run the test. I wasn't thinking of these tests as only a means to measure the _current_ performance, but as a tool to see how changes in the linear algebra system _modify_ performance. Consequently, what we really want is _good enough_ measurements of performance to be able to detect relative changes when tweaking the underlying system.

**Comment by jiahao** [comment]
> see how changes in the linear algebra system modify performance

I don't quite understand what you mean. Is this referring to how fast Julia is when linked against openBLAS, MKL, ATLAS, etc.? I think that would be quite useful to have.

**Comment by blakejohnson** [comment]
Sure, linking against various BLAS implementations, or making changes to the implementation such as threading parameters, thresholds, kernel choice, etc. 

I'm just saying that if you want something that is useful to measure changes, then it had better not take too long to run.

**Comment by jiahao** [comment]
We could have a quick benchmark set for testing one particular configuration, and a comprehensive benchmark set for automated testing of multiple configurations. (I can already see the Makefile nightmare that the latter would be, but it will probably be worth it.)

**Comment by blakejohnson** [comment]
More importantly, you could have two sets of test parameters: quick and accurate. The accurate parameters might test a more comprehensive set of problem sizes and with larger numbers of iterations.

**Comment by jiahao** [comment]
Yeah, I think that was what I meant to say.

**Comment by ViralBShah** [comment]
I am marking this as 0.3, as this will hopefully be part of work on improving various things related to linear algebra.

**Comment by KristofferC** [comment]
This seems to be mostly general discussion about benchmarking strategies which we now have a good system for with Nanosoldier. This also includes a number of different linear algebra benchmarks.
