### ISSUE TITLE
kron for more than 2 operands

### ISSUE THREAD

**Issue by Jutho** [JuliaLang/LinearAlgebra.jl#36]
As an associative operation, it would make sense to extend `kron` to an arbitrary number of arguments. I think adding these definitions to linalg/dense.jl would do the trick, but I leave it to the developers to choose the strategy that fits best with the multiple dispatch philosophy (hence no pull request):

``` julia
kron(a::Vector, args...) = kron(a,kron(args...))
kron(a::Matrix, args...) = kron(a,kron(args...))
kron(a::Number, args...) = kron(a,kron(args...))
```

Also, how would you feel of having a new binary operator ⊗ (U+2297) that refers to `kron`?

**Comment by jiahao** [comment]
There is an old issue about custom infix operators.

**Comment by staticfloat** [comment]
I believe the issue @jiahao is referring to is https://github.com/JuliaLang/julia/issues/552 (wow, all the way back in the triple-digits!)

**Comment by Jutho** [comment]
Indeed, I should have looked first. However, aside from the discussion of allowing infix operators and using unicode for them, it is interesting that StefanKarpinski mentions in JuliaLang/julia#552 that you can always do kron(A,B,C), which is not true (for me at least, with the latest Julia build).

**Comment by stevengj** [comment]
Putting aside the issue of infix operators, I think it would be great to have `kron` for more than 2 operands.   I would suggest following the model of the multi-operand `+` etc. code in `operators.jl` (lines 67–68), and define:

```
kron(a, b, c) = kron(kron(a,b), c)
kron(a, b, c, xs...) = kron(kron(kron(a,b),c), xs...)
```

**Comment by JeffBezanson** [comment]
An even simpler definition would be:

```
kron(a, b, c, xs...) = throw(MemoryError())
```

:)

**Comment by lsorber** [comment]
+1

**Comment by stevengj** [comment]
@JeffBezanson, a counterexample would be a Hadamard matrix, which can be defined as a Kronecker product of 2×2 matrices.  Since they are 2×2, you can afford to ⊗ a dozen of them before worrying about memory.  (Of course, you are better off representing the matrix implicitly and using [Hadamard.jl](https://github.com/stevengj/Hadamard.jl), but sometimes it's nice to play around with the full matrix.)
