### ISSUE TITLE
cholfact(SparseMatrixCSC) should give PosDefException if matrix is not SPD

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/LinearAlgebra.jl#39]
As reported on the mailing list, we should make sure that `cholfact(SparseMatrixCSC)` returns the PosDefException if the matrix is not symmetric and positive definite.

**Comment by jiahao** [comment]
The challenge in implementing this is twofold:
1. CHOLMOD does not always fail to factorize an indefinite matrix. When the usual `LL'` factorization fails, it tries to use the `sqrt`-avoiding `LDL'` variant. Example:
   
   ``` julia
   julia> cholfact(sparse([1.0 1.0; -1.0 1.0]))  
   CHOLMOD factor:  :  2-by-2
   scalar types: SuiteSparse_long, real, double
   simplicial, LDL'.
   ordering method used: AMD
          0:0
          1:1
   col: 0 colcount: 2
   col: 1 colcount: 1
   monotonic: 1
   nzmax 3.
   col 0: nz 2 start 0 end 2 space 2 free 0:
          0: 2
          1: 0
   col 1: nz 1 start 2 end 3 space 1 free 0:
          1: 2
   nz 3  OK
   ```
   
   Thus it is not correct to expect that a non-SPD matrix will always fail to be factorized by CHOLMOD.
2. CHOLMOD (at least, the version in SuiteSparse-4.2.1) appears to happily factorize unsymmetric matrices, even indefinite ones.
   
   ``` julia
   julia> Z=randn(58,58); cholfact(Z)
   ERROR: PosDefException(1)
   in cholfact! at linalg/factorization.jl:28
   in cholfact at linalg/factorization.jl:32
   julia> cholfact(sparse(Z))
   CHOLMOD factor:  :  58-by-58
   scalar types: SuiteSparse_long, real, double
   simplicial, LDL'.
   ordering method used: AMD
          0:0
   ...
   ```
   
   The return code of the `factorize()` function in `libcholmod` is `1 (CHOLMOD_TRUE)`.
   
   What is even more worrying is that `CHOLMOD` returns an `LL'` type factorization for `sparse(randn(60,60))` without signaling an error in the return code. (`sparse(randn(59,59))` returns `LDL'` type factorizations, which are at least plausible.)
   
   I haven't investigated further, but is possible that `CHOLMOD` only looks at half the matrix and assumes it to be symmetric. This would explain why `sparse(randn(59,59))` would work. However, I don't understand why `cholfact(sparse(randn(60,60)))` does what it does. But whatever the explanation, it is clear that the `CHOLMOD` wrappers need more sanity checking.

**Comment by ViralBShah** [comment]
Cc: @dmbates

**Comment by dmbates** [comment]
Sorry not to respond earlier.  I was ill.

I can check the details but my recollection is that for a simplicial factorization the default is LDL' whereas for a supernodal factorization it is LL'.  Unfortunately these options at not passed directly in the call to cholmod_analyze or cholmod_factorize but instead are set in the cholmod_common struct.

Regarding non-symmetric matrices, the convention is that when a symmetric matrix is passed it is the matrix that is factored whereas a nonsymmetric argument A indicates that AA' should be factored.

Obviously I should have done a better job of documenting this.

**Comment by jiahao** [comment]
@dmbates thanks for the explanations.

> I can check the details but my recollection is that for a simplicial factorization the default is LDL' whereas for a supernodal factorization it is LL'. Unfortunately these options at not passed directly in the call to cholmod_analyze or cholmod_factorize but instead are set in the cholmod_common struct.

So to fulfill the letter of the issue, it would be necessary to set `CHOLMOD_SUPERNODAL (== 2)` in `cholmod_common` and/or whatever else it takes to force an ordinary `LL'` factorization. The question is whether it is desirable to always throw a `PosDefException` or return a `LDL'` factorization when possible.

> Regarding non-symmetric matrices, the convention is that when a symmetric matrix is passed it is the matrix that is factored whereas a nonsymmetric argument A indicates that AA' should be factored.

It's clear that at the very least, we should check for the symmetry of sparse `M` in `cholfact(M)`, to make sure we know what we're computing.

Hope you're feeling better; these days, it also feels like all of greater Boston is snowed in with colds.

**Comment by ViralBShah** [comment]
@dmbates Hope you are feeling better.

We should also make this behaviour consistent across the dense and sparse matrices, to the extent possible.

**Comment by ViralBShah** [comment]
This is already documented, that the factorization is of `A*A'`.

**Comment by matthieugomez** [comment]
When A is not symmetric, `cholfact(A)` now returns "ERROR: ArgumentError: sparse matrix is not symmetric/Hermitian". What's the best way to compute the cholesky factorization for AA' now?

**Comment by tkelman** [comment]
We could potentially expose this under a separate name.

**Comment by matthieugomez** [comment]
Should I start a new issue for that?  I'd find it very valuable to be be able to symbolic factorize a rectangular matrix A (for instance, levenberg marquard requires to compute least square solution of a gradient multiple times). In the meantime, is there a way to do it?

**Comment by tkelman** [comment]
You should be able to call cholmod directly.
