### ISSUE TITLE
Bug in getindex{T}(obj::GeneralizedSVD{T}, d::Symbol)?

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/LinearAlgebra.jl#44]
in `getindex{T}(obj::GeneralizedSVD{T}, d::Symbol)` in `base/linalg/factorization.jl`, this block looks suspicious:

```
    if d == :R0 
        m = size(obj.U, 1)
        n = size(obj.Q, 1)
        if m - obj.k - obj.l >= 0
            return [zeros(T, obj.k + obj.l, n - obj.k - obj.l) obj.R]
        else
            return [zeros(T, obj.k + obj.l, n - obj.k - obj.l) obj.R]
        end 
    end 
```

It looks like there is a check for whether `obj.R` needs zero-padding, but the test is on `m - obj.k - obj.l` while one of the padded dimensions is `n - obj.k - obj.l`. In both cases, the return quantities are identical.

**Comment by andreasnoack** [comment]
You are right. The zero padding is the same, but it is slight hidden in the documentation for `dggsvd`. Fixed by a11f193318b9b0428d8bb608c5362b8df216ff54
