### ISSUE TITLE
Document separate symbolic and numerical factorizations in CHOLMOD

### ISSUE THREAD

**Issue by joachimdahl** [JuliaLang/LinearAlgebra.jl#47]
Currently it is not possible to separate the symbolic from the numerical factorization in CHOLMOD. It would be good to change this in a future version.

[ViralBShah: Reopened issue and marked it as a doc issue. Changed the title to reflect that as well.]

**Comment by ViralBShah** [comment]
Cc: @dmbates

**Comment by dmbates** [comment]
The `cholfact!` methods separate the numerical factorization from the symbolic.  There are several `cholfact!` methods that take a CholmodFactor object and update it according to the numeric values in a CholmodSparse object or a SparseMatrixCSC object.

Admittedly the documentation for these methods is more-or-less non-existent but the methods are there.

**Comment by joachimdahl** [comment]
You are right - sorry to have missed those.  They are exactly what I had in mind, so am closing the issue.

**Comment by kmsquire** [comment]
Instead of closing, why not change the title to indicate that those
functions need documentation?

**Comment by jiahao** [comment]
related: JuliaLang/LinearAlgebra.jl#39

**Comment by ViralBShah** [comment]
If I do this, am I reusing the symbolic factorization:

```
x = cholfact(speye(5))
y = cholfact!(x, 5*speye(5))
```

It appears so, but just wanted to verify here before updating the docs.

**Comment by dmbates** [comment]
Note to self: Don't try to comment on an issue when using a tablet.

I meant to write "@ViralBShah Yes, you are correct.  Calling `cholfact!(x, 5*speye(5))` will update x in place.  There should be no need to assign the result to `y`.
