### ISSUE TITLE
Slow sparse backward/forward substitution

### ISSUE THREAD

**Issue by ghost** [JuliaLang/LinearAlgebra.jl#49]
We are playing with the backward and forward substitution and comparing it to matlab.
Here are the results.
Can these operations run faster? An alternative is to hook Julia to sparsekit  and to use their backward/forward substitution

In Julia

```
ddx(n) = spdiagm((-ones(n), ones(n)),[0 1],n,n+1);
k = 32;
Div =[kron(speye(k),kron(speye(k),ddx(k))),
kron(speye(k),kron(ddx(k),speye(k))),
kron(ddx(k),kron(speye(k),speye(k)))];

A = Div*Div';
L = tril(A);
x = randn(size(L,1));
tic(); L\x; toc()
```

elapsed time: 0.064457582 seconds

In matlab

```
ddx = @(n) spdiags([-ones(n,1), ones(n,1)],[0,1],n,n+1);
k = 32;
Div =[kron(speye(k),kron(speye(k),ddx(k))), …
         kron(speye(k),kron(ddx(k),speye(k))), ...
         kron(ddx(k),kron(speye(k),speye(k)))];
A = Div*Div';
L = tril(A);
x = randn(size(L,1),1);
tic; L\x; toc
```

Elapsed time is 0.002886 seconds

**Comment by stevengj** [comment]
Are you running Matlab with a single core? (Launch `matlab` with the `-singleCompThread` option.)  Otherwise you may be comparing parallel to serial performance.

**Comment by andreasnoack** [comment]
I can confirm @ehaber99's finding. However, if copy/pasted the `Div` matrix is wrong in julia. The line breaks gives wrong concatenation compared to the MATLAB code.

**Comment by ghost** [comment]
I just tried the code and it works well for me.

I'd like to stress that the lower/upper solvers are essential for iterative solutions of linear systems.

**Comment by ViralBShah** [comment]
We probably need to detect triangular matrices and permutations of those and do the triangular solves.

**Comment by ViralBShah** [comment]
Cc @dmbates.

**Comment by joachimdahl** [comment]
Another possibility would be to explicitly call a triangular solve routine. The '\' operator can become too overloaded, checking for triangular systems, banded systems, definite systems, Toepltiz, etc., etc..

**Comment by ViralBShah** [comment]
Yes, `\` is typically quite overloaded. However, what is typically done is that one checks for the fast cases first and dispatch them away quickly - diagonal, triangular, permutations of triangular, and then move on to the more complex cases.

**Comment by ghost** [comment]
The following works well for symmetric matrices. For non symmetric matrices there is some thought
about addressing the entrees of the matrix efficiently.
I have a question - Is the CSC storage is the best idea? CSR may be better for many problems.

```
function backwardTriSolve(A,b)
# back substitution for symmetric matrices
n = length(b)

ncol, nrow = size(A)
if ncol!=nrow; error("A must be square"); end;
if n!=ncol; error("A must be nXn"); end;

x = zeros(n)

aa = A.nzval
ja = A.rowval
ia = A.colptr

diagt = 0

for i = 1:n
   xt = 0.0
   diag_exist = false

   j1 = ia[i]
   j2 = ia[i+1] - 1
   for j = j1:j2
      jcol = ja[j]
      if (jcol < i)
         xt = xt + aa[j]*x[jcol]
      elseif (jcol == i)
         diagt = aa[j]
         diag_exist = true
      end

   end
   if diag_exist == false; error("Diag does not exist"); end
   x[i] =  (b[i] - xt) / diagt
end


return x

end
```

And an experiment

```
A = sprandn(100000,100000,0.0001);
A = A'*A + speye(100000);
b = randn(100000);

tic();x=backwardTriSolve(A,b); toc()
```

elapsed time: 0.040072446 seconds

```
B = tril(A);
tic();x1 = B\b; toc()
```

elapsed time: 0.778964948 seconds

**Comment by ghost** [comment]
Just tried the latest code from anj/sparsesolve

```
tic(); B\x; toc()
```

elapsed time: 0.022925084 seconds

```
tic(); x = backwardTriSolve(A,b); toc()
```

elapsed time: 0.041584022 seconds

Nice job!!!

**Comment by lruthotto** [comment]
Hi there!

I think I came up with an efficient Julia solution for this problem. Find codes for forward and backward substitution below. As Eldad,  I compared it with the code from anj/sparsesolve. On my machine (MacBook Pro 2.6 GhZ Intel i7) I get the following timings:

```
B = triu(A);
tic(); x2 = B\b; toc();
```

elapsed time: 0.025373589 seconds

```
tic(); x1 = bwdTriSolve(B,b); toc();
```

elapsed time: 0.025363095 seconds

Similarly

```
B = tril(A);
tic(); x1 = fwdTriSolve(B,b); toc();
```

elapsed time: 0.024063655 seconds

```
tic(); x2 = B\b; toc();
```

elapsed time: 0.02189521 seconds

And so I guess, my function is about as efficient as the ones in anj/sparsesolve.

Here is my code:

```
function fwdTriSolve(A,b)
# forward substitution for CSC matrices
n = length(b)
ncol, nrow = size(A)
if ncol!=nrow; error("A must be square"); end;
if n!=ncol; error("A must be nXn"); end;

x = zeros(n)

aa = A.nzval
ja = A.rowval
ia = A.colptr

for j=1:n
   i1 = ia[j]
   i2 = ia[j+1]-1
   x[j] = (b[j]-x[j])/aa[i1]
   for i = i1+1:i2
      x[ja[i]] += aa[i]*x[j]
   end
end
return x
end


function bwdTriSolve(A,b)
# backward substitution for CSC matrices
n = length(b)
ncol, nrow = size(A)
if ncol!=nrow; error("A must be square"); end;
if n!=ncol; error("A must be nXn"); end;

x = zeros(n)

aa = A.nzval
ja = A.rowval
ia = A.colptr

for j=n:-1:1
   i1 = ia[j]
   i2 = ia[j+1]-1
   x[j] = (b[j]-x[j])/aa[i2]
   for i = i2-1:-1:i1
      x[ja[i]] += aa[i]*x[j]
   end
end
return x
end

```

**Comment by andreasnoack** [comment]
JuliaLang/julia#4985 solved this
