### ISSUE TITLE
LAPACK 3.5.0

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/LinearAlgebra.jl#50]
LAPACK 3.5.0 is released. We should update to it once openblas does the same.

xianyi/openblas#324

**Comment by ViralBShah** [comment]
http://www.netlib.org/lapack/lapack-3.5.0.html

**Comment by jiahao** [comment]
It's getting to the point that we should decide how to handle LAPACK versioning issues for user-specified external LAPACKs. I very much like supporting cosine-sine decompositions, for example, but all that is very recent.

**Comment by andreasnoack** [comment]
OpenBLAS has been using 3.5 for a long time now. Who is affected by the LAPACK in deps? Is it when compiling with Accelerate? MKL and OpenBLAS have their own LAPACKs.

**Comment by ViralBShah** [comment]
Only on their RCs and develop branches, I believe. Not in 0.2.8 that we use. Once 0.2.9 releases, we could update to LAPACK 3.5.0. We build it mainly when using Accelerate, but it is useful for debugging.

**Comment by jiahao** [comment]
Closed by JuliaLang/julia#7213.
