### ISSUE TITLE
sketchy complex expm result

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/LinearAlgebra.jl#51]
Julia:

``` julia
julia> A = [ 0. 0. 0. 0. ; 0. 0. -im 0.; 0. im 0. 0.; 0. 0. 0. 0.]
4x4 Array{Complex{Float64},2}:
 0.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0-1.0im  0.0+0.0im
 0.0+0.0im  0.0+1.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im

julia> expm(A)
4x4 Array{Complex{Float64},2}:
 0.0+0.0im      0.0+0.0im      0.0+0.0im  0.0+0.0im
 0.0+0.0im  1.54308+0.0im   0.0-1.1752im  0.0+0.0im
 1.0+0.0im   0.0+1.1752im  1.54308+0.0im  0.0+0.0im
 0.0+0.0im      0.0+0.0im      0.0+0.0im  1.0+0.0im
```

Matlab:

``` matlab
>> A = [ 0. 0. 0. 0. ; 0. 0. -i 0.; 0. i 0. 0.; 0. 0. 0. 0.]

A =

        0                  0                  0                  0
        0                  0                  0 - 1.0000i        0
        0                  0 + 1.0000i        0                  0
        0                  0                  0                  0

>> expm(A)

ans =

   1.0000                  0                  0                  0
        0             1.5431                  0 - 1.1752i        0
        0                  0 + 1.1752i   1.5431                  0
        0                  0                  0             1.0000
```

**Comment by StefanKarpinski** [comment]
Discussion: https://groups.google.com/forum/#!topic/julia-users/lcfes0NhtDQ

cc: @ViralBShah, @andreasnoackjensen, @alanedelman, @stevengj

**Comment by StefanKarpinski** [comment]
This is where it's happening:

https://github.com/JuliaLang/julia/blob/master/base/linalg/dense.jl#L199-L288

That's as far as I think I can get debugging this.

**Comment by acroy** [comment]
I think rcswap is the issue. The permutation of column and row should probably be done sequentially not in one go?
Anyways, this seems to fix the problem:

```
function rcswap!{T<:Number}(j::Integer, jp::Integer, X::StridedMatrix{T})
    for k in 1:size(X, 1)
        tmp     = X[k,j]
        X[k,j]  = X[k,jp]
        X[k,jp] = tmp       
    end
    for k in 1:size(X, 2)
        tmp     = X[j,k]
        X[j,k]  = X[jp,k]
        X[jp,k] = tmp
    end
end
```

BTW: In expm! there seems to be an additional typo in line 282:
`(ilo-1):1:-1` should be `(ilo-1):-1:1` ?!

**Comment by StefanKarpinski** [comment]
Nice! I've made a patch from those changes and can confirm that it fixes the issue. If you want, I can make you the author of the patch so you get official credit, but I need a name and email to do that through git. If not, I can just link to your github username in the commit message.

**Comment by acroy** [comment]
I just learned that the scaling in expm doesn't work properly. I cannot provide a good (= small) example. The matrix I have here is 256x256 ... I would suggest to reopen this issue until the problem is confirmed?

I suggest the following fix for lines L260-L280 in dense.jl (https://github.com/JuliaLang/julia/blob/master/base/linalg/dense.jl#L260-L280):

```
    for j = ilo:ihi
        scj = scale[j]
        for i = 1:n
            X[j,i] *= scj
        end
        for i = 1:n
            X[i,j] /= scj
        end
    end
```

(Motivated by the documentation of xGEBAL, see http://www.netlib.no/netlib/lapack/double/dgebal.f)

Alternatively, scaling can be switched off in L202, i.e.

```
    ilo, ihi, scale = LAPACK.gebal!('P', A)    # modifies A, permutations only
```

**Comment by acroy** [comment]
Ok, here is an example:

```
julia> expm([0 10 0 0; -1 0 0 0; 0 0 0 0; -2 0 0 0])
4x4 Array{Float64,2}:
 -0.999786    -0.0654071  0.0  0.0
  0.00654071  -0.999786   0.0  0.0
  0.0          0.0        1.0  0.0
  0.0130814   -0.999893   0.0  1.0
```

while MATLAB gives

```
ans =

   -0.9998   -0.0654         0         0
    0.0065   -0.9998         0         0
         0         0    1.0000         0
    0.0131   -3.9996         0    1.0000
```

**Comment by StefanKarpinski** [comment]
Seems like a different issue.

**Comment by acroy** [comment]
Maybe. This time it is connected to the scaling and not the permutations. Shall I open a new issue then?

**Comment by StefanKarpinski** [comment]
No, I guess we can just reopen this.

**Comment by porterjamesj** [comment]
Interesting; I've been seeing some weird discrepancies between code I've been writing (which makes heavy use of expm) and a reference implementation. Hopefully this explains it!

**Comment by ViralBShah** [comment]
Cc @dmbates

**Comment by acroy** [comment]
Looking at the description of xGEBAL, the current un-doing of the scaling is certainly wrong. As a short term fix scaling could be switched off, but my fix seems to work as well. (BTW, the element (4,2) of matrix exponential given above is supposed to be `2 cos( sqrt(10) ) - 2` ).

**Comment by ViralBShah** [comment]
Can you submit a PR with your fix? It would be best to fix this rather than disabling scaling.

**Comment by JeffBezanson** [comment]
Is this fixed now?

**Comment by jiahao** [comment]
The two examples in this issue appear to be correct now.

**Comment by ViralBShah** [comment]
Yes, I merged this stuff and also added the tests.

**Comment by ViralBShah** [comment]
Fixed in https://github.com/JuliaLang/julia/pull/5151
