### ISSUE TITLE
MKL Test error

### ISSUE THREAD

**Issue by lindahua** [JuliaLang/LinearAlgebra.jl#53]
Here is what it shows when I did `make testall`:

``` julia
dhlin@julia:make testall
    JULIA test/all
    From worker 2:       * core
    From worker 5:       * strings
    From worker 4:       * numbers
    From worker 7:       * collections
    From worker 8:       * hashing
    From worker 6:       * unicode
    From worker 3:       * keywordargs
    From worker 9:       * remote
    From worker 9:       * iobuffer
    From worker 9:       * arrayops
    From worker 3:       * linalg
    From worker 8:       * blas
exception on 3: ERROR: BoundsError()
 in getindex at linalg/factorization.jl:166
 in cond at linalg/factorization.jl:218
 in cond at linalg/dense.jl:489
 in anonymous at no file:9
 in runtests at /Users/dhlin/julia/test/testdefs.jl:5
 in anonymous at multi.jl:834
 in run_work_thunk at multi.jl:575
 in anonymous at task.jl:834
while loading linalg.jl, in expression starting on line 6
ERROR: BoundsError()
 in anonymous at multi.jl:1384
while loading linalg.jl, in expression starting on line 6
while loading /Users/dhlin/julia/test/runtests.jl, in expression starting on line 21

make[1]: *** [all] Error 1
make: *** [testall] Error 2
```

This is latest master linked with MKL:

```
Julia Version 0.3.0-prerelease+460
Commit 9cdf7d4 (2013-12-14 18:48 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.0.0)
  WORD_SIZE: 64
  BLAS: libmkl_rt
  LAPACK: libmkl_rt
  LIBM: libopenlibm
```

I suspect this is related to JuliaLang/LinearAlgebra.jl#52. And, it is possibly caused by incorrect `BaseInt` size, as @jiahao mentioned.

cc: @ViralBShah

**Comment by ViralBShah** [comment]
Also Cc: @andreasnoackjensen

**Comment by andreasnoack** [comment]
I can reproduce @lindahua's error but it disappears if either I compile with `USE_BLAS64=0` or run `export MKL_INTERFACE_LAYER=ILP64` before the tests. I guess it would be good, if julia could detect the interface at runtime as has been mentioned earlier.

**Comment by lindahua** [comment]
compile with `USE_BLAS64` causes errors on tests on ARPACK as

``` julia
exception on 2: ERROR: ARPACKException(-3)
 in aupd_wrapper at linalg/arpack.jl:52
 in eigs at linalg/arnoldi.jl:43
 in anonymous at arpack.jl:17
 in runtests at /Users/dhlin/julia/test/testdefs.jl:5
 in anonymous at multi.jl:834
 in run_work_thunk at multi.jl:575
 in anonymous at task.jl:834
while loading arpack.jl, in expression starting on line 1
ERROR: ARPACKException(-3)
 in anonymous at multi.jl:1384
while loading arpack.jl, in expression starting on line 1
while loading /Users/dhlin/julia/test/runtests.jl, in expression starting on line 21

make[1]: *** [all] Error 1
make: *** [testall] Error 2
```

Looks like, MKL is using 32-bit int, while Arpack is still using 64-bit int. Forcing BlasInt to be 64-bit seems to be problematic for Arpack.

The other workaround, that is setting environment variable `export MKL_INTERFACE_LAYER=ILP64`, do works. In this case, Blas, Lapack, and Arpack all use 64-bit Int.

I think it would be useful to document this (for MKL users).

**Comment by ViralBShah** [comment]
We do use arpack with 64 bit Openblas.

**Comment by jiahao** [comment]
I wonder why the build-time check I put in didn't catch this. Maybe the expecting 64-bit but returning 32-bit test needs to be changed to `info >> 32 == 2` (from `info == 2^33`); the extra word may not be purely 0.

**Comment by ViralBShah** [comment]
What if we just link directly to `libmkl_intel_ilp64.so` instead of `libmkl_rt.so` if `USE_BLAS64=1` ?

**Comment by ViralBShah** [comment]
This is what I am attempting, but unsuccessfully so far:

```
diff --git a/Make.inc b/Make.inc
index a29ece6..f077e4d 100644
--- a/Make.inc
+++ b/Make.inc
@@ -444,9 +444,15 @@ endif
 ifeq ($(USE_MKL), 1)
 USE_SYSTEM_BLAS=1
 USE_SYSTEM_LAPACK=1
+ifeq ($(USE_BLAS64),1)
+LIBBLASNAME = libmkl_intel_ilp64
+LIBLAPACKNAME = libmkl_intel_ilp64
+MKL_LDFLAGS = -L$(MKLLIB) -lmkl_intel_ilp64
+else
 LIBBLASNAME = libmkl_rt
 LIBLAPACKNAME = libmkl_rt
 MKL_LDFLAGS = -L$(MKLLIB) -lmkl_rt
+endif
 ifneq ($(strip $(MKLLIB)),)
   ifeq ($(OS), Linux)
     RPATH_MKL = -Wl,-rpath,$(MKLLIB)
```

I get:

```
julia 10:41:14 {master} ~/julia-mkl$ ./julia
fatal: error thrown and no exception handler available.
ErrorException("could not load module libmkl_intel_ilp64: libmkl_intel_ilp64: cannot open shared object file: No such file or directory")
```

**Comment by ViralBShah** [comment]
Cc: @staticfloat

**Comment by ViralBShah** [comment]
Here is what we can do: If `USE_BLAS64` is set, then we should make sure that `MKL_INTERFACE_LAYER=ILP64` is set during the build. This is not perfect, but at least should work for folks who build themselves. Distributing MKL with Julia is not easy anyways as of now - so perhaps we can worry about that later.

**Comment by ViralBShah** [comment]
@lindahua Please see the above PR that should address the ARPACK crash.

**Comment by lindahua** [comment]
I will do a check later. 

As I am currently working on a PR to Julia, I have switched to using OpenBLAS, mainly to ensure that the tests do not fail.

**Comment by ViralBShah** [comment]
I usually keep a separate `julia-mkl` directory for use with MKL.
