### ISSUE TITLE
Triangular linalg test fails for me

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/LinearAlgebra.jl#55]
I get the following failure in the tests for BigFloat Triangular (modified to show the norms):

```
norm(-(x,tx)) => 7.464464849465350874221853329497062064309498633804273690161186521156177549584086e-13 with 256 bits of precision

max(*(condM,norm(-(*(TM,tx),b)),norm(x)),*(*(2,condM),max(eps(relty),eps()))) => 5.77116908235338382232313017320096508455673500748162041418254375457763671875e-13 with 256 bits of precision

ERROR: test failed: :((norm(-(x,tx))<=max(*(condM,norm(-(*(TM,tx),b)),norm(x)),*(*(2,condM),max(eps(relty),eps())))))
 in error at error.jl:21
 in default_handler at test.jl:19
 in do_test at test.jl:39
 in anonymous at no file:592
while loading /home/jeff/src/julia2/julia/test/linalg.jl, in expression starting on line 571
```

It's off by a little bit.

BTW, great to have all this new special matrix functionality.

**Comment by andreasnoack** [comment]
I cannot reproduce this on OS X or OpenSUSE.

**Comment by nalimilan** [comment]
I see this too with the commits from the last few days, when building my RPM package on Fedora 20 (using system libraries).

**Comment by lindahua** [comment]
I have the same problem on Mac OS X with latest commit. 

What about we just relax the criterion a little bit?

**Comment by jiahao** [comment]
I consulted Golub and Van Loan and it looks like the original test was missing a factor of 4. I've reimplemented the forward error check and it seems to be OK now.
