### ISSUE TITLE
inv of Adjoint is type-unstable

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/LinearAlgebra.jl#585]
```julia
julia> using Test

julia> @inferred inv([1 2; 3 4]')    # same with Matrix{Float64} input
ERROR: return type Array{Float64,2} does not match inferred return type Any
```

**Comment by andreasnoack** [comment]
It's because the fallback `inv` uses `factorize` which is inherently type unstable. A solution could either be to use `lu` instead or to add a special `inv(A::Adjoint) = Adjoint(inv(parent(A)))` method.

**Comment by StefanKarpinski** [comment]
> add a special `inv(A::Adjoint) = Adjoint(inv(A))` method.

This seems like a pretty good general solution but shouldn't it be `adjoint(inv(A))` so that if `inv` returns an adjoint the outer `adjoint` call can undo an inner adjoint wrapper?
