### ISSUE TITLE
spzeros inconsistent with zeros

### ISSUE THREAD

**Issue by mlubin** [JuliaLang/LinearAlgebra.jl#62]
`zeros(n)` returns an `n`-element vector, while `spzeros(n)` returns an `n` x `n` matrix. This seems inconsistent and a potential source of bugs when translating dense code to sparse code. I'd vote for changing it to return an `n` x `1` sparse matrix, or just removing this method to prevent confusion.

**Comment by IainNZ** [comment]
I'm guessing the spzeros(n) is a hangover from MATLAB, where zeros(n) at least is an n-by-n matrix if I recall correctly.

**Comment by johnmyleswhite** [comment]
+1 for more consistency between `zeros` and `spzeros`.

**Comment by ViralBShah** [comment]
Matlab does not have spzeros, IIRC. It is entirely our creation.

**Comment by ViralBShah** [comment]
Given that we do not have a sparse vector implementation, we should just support the two argument version only.

**Comment by jiahao** [comment]
The closest thing I can think of in Matlab is [spalloc](http://www.mathworks.com/help/matlab/ref/spalloc.html), which lacks a single-argument call signature.

> Given that we do not have a sparse vector implementation, we should just support the two argument version only.

Yeah, let's just do that.
