### ISSUE TITLE
Slow sparse matrix norms

### ISSUE THREAD

**Issue by lruthotto** [JuliaLang/LinearAlgebra.jl#64]
We are comparing the performance of computing norms of sparse matrices between Julia (Commit 42b3583)  and Matlab (R2013a, single computational thread)  and found the current implementation to be very(!!) slow.

Julia:

```
A = sprandn(10000,10000,.0001)
tic(); norm(A,Inf); toc()
```

elapsed time: 1.065244501 seconds

MATLAB: 

```
A = sprandn(10000,10000,.0001)
tic;  norm(A,'inf'); toc
```

Elapsed time is 0.000591 seconds.

We observed a similar performance gap for the 1-norm. The  Frobenius norm does not seem to be implemented for sparse matrices.

**Comment by johnmyleswhite** [comment]
Right now the norm functions is falling back to an AbstractArray definition, which I think loops over linear indices. This needs a custom implementation to be fast.

**Comment by lruthotto** [comment]
How can I see this? Is there a quick way to find the filename and line number for the function Julia's dispatcher selects for given input types?

**Comment by johnmyleswhite** [comment]
```
julia> A = sprandn(10000,10000,.0001)
10000x10000 sparse matrix with 9998 Float64 nonzeros:
    [2909 ,     2]  =  -0.153745
    [3560 ,     3]  =  0.125012
    [6440 ,     3]  =  -0.967166
    [7999 ,     3]  =  0.126193
    [5997 ,     4]  =  -0.00124763
    [9818 ,     4]  =  0.498594
    [8672 ,     5]  =  0.329685
    ⋮
    [9003 ,  9994]  =  -0.269874
    [2019 ,  9995]  =  0.847843
    [9803 ,  9995]  =  0.0658022
    [1650 ,  9996]  =  -0.106305
    [2096 ,  9997]  =  1.37328
    [8912 ,  9998]  =  0.609608
    [1854 , 10000]  =  -0.234208
    [4103 , 10000]  =  -0.153974

julia> @which norm(A, Inf)
norm{T}(A::AbstractArray{T,2},p::Number) at linalg/generic.jl:69
```

**Comment by lruthotto** [comment]
Thanks for this hint, John! 

I think I came up with some taylored implementation at least for the 1-norm, Inf-norm and Frobenius norm.

```
function normfro(A::SparseMatrixCSC)
    return real(sqrt(dot(A.nzval,A.nzval)))
end

function norm(A::SparseMatrixCSC,p::Number=1)
    if p==1
        aa = A.nzval
        ja = A.rowval
        ia = A.colptr
        nA = 0.0
        for j=1:size(A,2)
            colSum = 0.0
            i1 = ia[j]
            i2 = ia[j+1]-1
            for i = i1:i2
                colSum += abs(aa[i])
            end
            nA = (colSum>nA)? colSum : nA
        end
    elseif p==Inf
        aa = A.nzval
        ja = A.rowval
        ia = A.colptr
        rowSum = zeros(size(A,1))
        for j=1:size(A,2)
            i1 = ia[j]
            i2 = ia[j+1]-1
            for i = i1:i2
                rowSum[ja[i]] += abs(aa[i])
            end
        end
        nA = maximum(rowSum)
    end
    return nA
end
```

This gives for the above example:

```
@time norm(A,Inf)
```

elapsed time: 0.000134432 seconds (80168 bytes allocated)

```
@time norm(A,1)
```

elapsed time: 0.000108226 seconds (208 bytes allocated)

```
@time normfro(A)
```

elapsed time: 9.781e-6 seconds (64 bytes allocated)

If you like the code, take it, modify it and put it into Base!

**Comment by JeffBezanson** [comment]
@lruthotto Thanks! You should fork our repository, edit that code into `base/sparse/sparsematrix.jl`, and issue a pull request. That way you get credit as the author of the code, and it will be easier to provide other fixes like this in the future.

**Comment by pao** [comment]
Appears to be superceded by JuliaLang/julia#5822.
