### ISSUE TITLE
bug in nonzeros

### ISSUE THREAD

**Issue by ghost** [JuliaLang/LinearAlgebra.jl#68]
I believe that there is a bug in nonzeros:

TT = sprandn(5,5,0.1)
5x5 sparse matrix with 3 Float64 nonzeros:
    [1, 2]  =  -0.518808
    [1, 3]  =  2.92795
    [2, 4]  =  -0.496715

julia> nonzeros(TT)
MethodError(nonzeros,(
5x5 sparse matrix with 3 Float64 nonzeros:
    [1, 2]  =  -0.518808
    [1, 3]  =  2.92795
    [2, 4]  =  -0.496715,))

**Comment by jiahao** [comment]
Works for me.

``` julia
julia> TT=sprandn(5,5,0.1)
5x5 sparse matrix with 3 Float64 nonzeros:
    [1, 2]  =  -0.4045
    [3, 3]  =  -1.23355
    [4, 4]  =  -0.283405

julia> nonzeros(TT)
3-element Array{Float64,1}:
 -0.4045  
 -1.23355 
 -0.283405

julia> versioninfo()
Julia Version 0.3.0-prerelease+1350
Commit 59acba9* (2014-01-31 23:44 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.0.2)
  CPU: Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY)
  LAPACK: libopenblas
  LIBM: libopenlibm
```

Could you show the output of `versioninfo()` on your machine?

**Comment by JeffBezanson** [comment]
Looks like a transient thing; reopen if this is reproducible.

**Comment by ivarne** [comment]
@JeffBezanson Regular github users can not reopen issues, if they do not have (commit?) access to the repo. Some users might be confused when they are asked to do something they do not have access to do.

**Comment by JeffBezanson** [comment]
Good point; hopefully they will post a comment in that case.
