### ISSUE TITLE
Implement Givens plane rotation

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/LinearAlgebra.jl#7]
Matlab has `planerot` for Givens plane rotations.

Although BLAS has `xROTG`, faster code can be achieved perhaps by just translating this into julia.

http://www.netlib.org/blas/drotg.f

**Comment by andrioni** [comment]
``` julia
function planerot{T<:Real}(x::Vector{T})
    if length(x) != 2
        error()
    end
    da, db = x
    roe = db
    if abs(da) > abs(db)
       roe = da
    end
    scale = abs(da) + abs(db)
    if scale == 0
        c = 1.
        s = 0.
        r = 0.
    else
        r = scale * sqrt((da/scale)^2 + (db/scale)^2)
        r = sign(roe) * r
        c = da/r
        s = db/r
    end
    return [c s; -s c], [r, 0.]
end
```

A fairly literal translation from Fortran (and more efficient than calling the BLAS function directly, according to my tests). Where should this go? `linalg/generic.jl`?

**Comment by ViralBShah** [comment]
Yes, `linalg/generic.jl` is perfect - thanks for doing it this quick! Could you add a couple of tests also, and submit a pull request?

**Comment by andreasnoack** [comment]
Some time ago I briefly had a look at 

http://www.netlib.org/lapack/lawnspdf/lawn148.pdf

Maybe the LAPACK plane rotation is preferred to the implementation in BLAS.

How would people use the rotations after calculating them? I wondered if planerot should return a plane rotation type.

**Comment by jiahao** [comment]
bump

Now that JuliaLang/julia#5109 is merged, `planerot` should be a thin wrapper around `Givens`

**Comment by andreasnoack** [comment]
I wonder how useful it is to have the 2x2 matrix constructed compared to just returning the tuple `c,s,r` which `givensAlgorithm` returns now. We could consider renaming `givensAlgorithm`.

**Comment by ViralBShah** [comment]
I agree - MATLAB's `planerot` is not a great API.

**Comment by jiahao** [comment]
Let's just close this then.

**Comment by ViralBShah** [comment]
We now have this capability, but we do not need `planerot` as in MATLAB.
