### ISSUE TITLE
Linear solver on lower triangular matrix linalg test failing

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/LinearAlgebra.jl#70]
Tests are failing on my mac at 6e5ac65910237a85f11a50ca9f7c90b13895dda3:

```
exception on 3: ERROR: assertion failed: |:(*(tril(a),x)) - b| <= 0.00011920928955078125
  :(*(tril(a),x)) = 1   5
4   1
4   1.0000001
5.0000005   1
2.0000002   4.9999995
4.0000005   2.9999986
2.9999993   3.0000007
4.9999967   3.000018
2.9999926   3.9999893
4.0000024   4.999778

  b = 1 5
4   1
4   1
5   1
2   5
4   3
3   3
5   3
3   4
4   5

  difference = 0.00022220612 > 0.00011920928955078125
 in error at error.jl:22
 in test_approx_eq at test.jl:68
 in anonymous at no file:200
 in runtests at /Users/viral/julia/test/testdefs.jl:5
 in anonymous at multi.jl:834
 in run_work_thunk at multi.jl:575
 in anonymous at task.jl:834
while loading linalg.jl, in expression starting on line 23
ERROR: assertion failed: |:(*(tril(a),x)) - b| <= 0.00011920928955078125
  :(*(tril(a),x)) = 1   5
4   1
4   1.0000001
5.0000005   1
2.0000002   4.9999995
4.0000005   2.9999986
2.9999993   3.0000007
4.9999967   3.000018
2.9999926   3.9999893
4.0000024   4.999778

  b = 1 5
4   1
4   1
5   1
2   5
4   3
3   3
5   3
3   4
4   5

  difference = 0.00022220612 > 0.00011920928955078125
 in anonymous at multi.jl:1384
while loading linalg.jl, in expression starting on line 23
while loading /Users/viral/julia/test/runtests.jl, in expression starting on line 23

make[1]: *** [all] Error 1
make: *** [testall] Error 2
```

**Comment by staticfloat** [comment]
Dup of JuliaLang/LinearAlgebra.jl#69

**Comment by jiahao** [comment]
This is actually _not_ a dupe; the test that is failing is different. However, I'm having trouble reproducing it.

**Comment by staticfloat** [comment]
Aha, you're right!  This is the error I've been seeing for a couple days so I assumed it was the same as the one I linked to, turns out I just never actually saw JuliaLang/LinearAlgebra.jl#69 on my machines!

I can reproduce this one consistently.  (It happens on `criid`, my build mac mini for the OSX nightlies).  If you need any info, just let me know.

**Comment by jiahao** [comment]
The root problem should be JuliaLang/LinearAlgebra.jl#67. I'll try to post a correct error bound shortly.

**Comment by jiahao** [comment]
Most of the linear algebra tests look superficially very similar and fail similarly, which is a problem. But the linalg test suite now spits out more detailed information if you set `debug = true` at the beginning of the file. This might be useful to note going forward as more of these magic numbers are deprecated.
