### ISSUE TITLE
linalg tests take too long

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/LinearAlgebra.jl#74]
Don't get me wrong: this kind of thorough testing is great. But at this point it is slowing us down a bit. We should consider dialing down some sizes or iteration counts, or splitting up the suite so different parts of it can run in parallel. Some of the loops could also potentially be made `@parallel`.

**Comment by jiahao** [comment]
Mostly a dupe of the conversation that hijacked JuliaLang/julia#5596.

**Comment by jiahao** [comment]
One of the least disruptive things we can do right now is to break up `tests/linalg.jl` into two pieces, the first testing operations over generic dense and triangular matrices, and the second testing all the special matrix types (`Tridiagonal`, etc.). You could almost exactly break up the tests this way by splitting the file somewhere around the halfway mark.

Parallelizing and/or dividing up the test suite further is quite likely to break some tests due to the need to readjust thresholds (#5605), and it will be a major task to clean up the carnage.

cc: @andreasnoackjensen @amitmurthy

**Comment by jiahao** [comment]
Quick comment: the test suite has gotten a lot more extensive since we are now starting to test generic linear algebra routines over `eltype`s that extend far beyond `BlasFloat`, like `Float16` and `Rational`s.

**Comment by andreasnoack** [comment]
I have just tried to make all the `for` loops over `eltype` `@parallel` and it only required minor modifications. The linalg tests still spend more time than all the other tests together.

I think the main time consumer is the compilation of the many different functions: different element types, different matrix types, access to intermediate results like LU, QR and Hessenberg, and finally a lot of functions handling promotion. The actual calculations are tiny and generally not repeated. One symptom of this is that julia allocates around 42 mb of RAM when launched and 360 mb after the linalg tests (and after gc).

**Comment by timholy** [comment]
How about doing something like this:

```
ELTYPES = (Float16, Float32, Float64, Complex32, Complex64, Complex128, BigFloat, Int)
pmap(run_linalgtests, ELTYPES)
```

That way each worker may only have to compile functions for one element type. For blocks that should not be tested with a particular element type, you could enclose them with a

```
if ELTYPE <: BlasFloat
    # run the test
end
```

for example.

**Comment by jiahao** [comment]
The bottleneck is in the jitting of the tests, not their execution, so parallelizing over eltypes doesn't actually help (unless we have a way of parallelizing the compilation also). Breaking up the tests, viz. JuliaLang/julia#5751, is really the way to go here imo.

**Comment by StefanKarpinski** [comment]
If that's the case, how does parallelizing over eltypes not help? That way each process only needs to JIT code for a subset of the eltypes, instead of for all of them.

**Comment by jiahao** [comment]
I recall @andreasnoackjensen trying something alone those lines with @parallel for loops, but the performance wasn't great?

**Comment by timholy** [comment]
If you just surround each block of tests with `@parallel`, then in every process each block is going to be randomly assigned a type. So for block1, a given process might get `Float64`, but for block2 it might get `Complex32`. But when it goes to see if the `Complex32` results are correct, it has to recompile functions that were already compiled for `Float64` during block1.

If instead each block in a given process is always assigned `Complex32`, then that's just about the only version that has to be compiled (in that process) for all the linalg functions. Seems like it would save a lot.

**Comment by amitmurthy** [comment]
```
for eltya in (Float16, Float32, Float64, Complex32, Complex64, Complex128, BigFloat, Int)
    for eltyb in (Float16, Float32, Float64, Complex32, Complex64, Complex128, Int)
.........
    end
end
```

@timholy difficult to efficiently split this one! Most of the others can be optimized as per your solution, but the above would probably compile the lot - at least on one process.

**Comment by timholy** [comment]
You could chunk it:

```
for j = 1:3:length(ELTYPESA)
   eltypesa = ELTYPESA[j:min(j+2,length(ELTYPESA))]
   for i = 1:3:length(ELTYPESB)
      eltypesb = ELTYPESB[i:min(i+2,length(ELTYPESB))]
      # run the test on eltypesa, eltypesb
   end
end
```

(I never thought I'd see `gemm`-style thinking in combination with JITting code!)

**Comment by jiahao** [comment]
JIT pb - now available in smooth and chunky

**Comment by kmsquire** [comment]
@jiahao, stop that, my office mates are looking at me strangely for laughing out loud... ;-D

**Comment by jiahao** [comment]
I'd tell you more about the secret remote groan program, but thanks to the current climate, I'm somewhat afraid of being snowed in.

**Comment by timholy** [comment]
Wow, that was quite a masterpiece of multiple meanings!

**Comment by Keno** [comment]
These still take uncomfortably long, especially since I don't actually know if progress is being made

**Comment by jiahao** [comment]
Which is why this issue is still open. The current tests are too fragile to decompose further (#5751).

Currently, if you wanted to know more details about the linalg tests, you can turn on additional printouts by setting `debug=true` in `linalg1.jl` and `linalg2.jl`.

**Comment by timholy** [comment]
As an update, I spent some time last night trying my "chunked" strategy. At least the way I was splitting it up, it didn't help. I suspect that several of the types are getting converted to `Float32` or `Float64` for core algorithms and so there's more overlap than I was accounting for. It still may be workable with more effort, but the initial results were not promising, so I don't think this should be a priority.

I also did encounter the effects of the fragile tests---I suspect they've been tuned to work based on the particular random sequence generated. Been there myself, and obviously this isn't remotely easy to get right. But it does make further experimentation a bit challenging.

**Comment by amitmurthy** [comment]
Just to get an idea of the JIT time vs actual run time, here are timings of repeat execution on the same processor:

```
linalg1 (first run)
elapsed time: 65.49706348 seconds (3179144348 bytes allocated)
linalg1 (second run)
elapsed time: 2.97498147 seconds (311530740 bytes allocated)



linalg2 (first run)
elapsed time: 60.525306587 seconds (4278960060 bytes allocated)
linalg2 (second run)
elapsed time: 25.239610881 seconds (2759375352 bytes allocated)
```

**Comment by timholy** [comment]
I was moments away from doing the same test. Thanks for saving my poor laptop CPU :smile:.

Perhaps `linalg1` should be added to `perf`? In all seriousness. (Unless we have another explicit performance test for JIT time.)

**Comment by jiahao** [comment]
Can we precompile the tests as a module of some sort?

**Comment by jiahao** [comment]
Is it just me, or is the linalg test suite now significantly slower to run with the latest batch of codegen changes? I don't remember linalg1 taking 5.5 minutes on my machine.

**Comment by tkelman** [comment]
Not just you. My AppVeyor runs are now regularly timing out at 30 minutes (download deps + build + tests, all on a single-core VM) where a week or two ago they finished fine in around 21-25 minutes.

**Comment by cbecker** [comment]
@jiahao could you profile it to see where the bottleneck is appearing?
I tried http://speed.julialang.org/ but something seems to be wrong.

**Comment by mschauer** [comment]
Linalg1.jl still tests the same functions with the same arguments several times over.
For example

```
debug && println("singular value decomposition")
    if eltya != BigFloat && eltyb != BigFloat # Revisit when implemented in julia
        usv = svdfact(a)
        @test_approx_eq usv[:U]*scale(usv[:S],usv[:Vt]) a
    end
```

only depends on `a` and `eltya` and gets called for 5 times (`for eltyb in (Float32, Float64, Complex64, Complex128, Int)`).  (Ok, that does not shave precompilation time.)

**Comment by andreasnoack** [comment]
The problems are so small that the extra calls don't matter. The time is consumed by the compilation.

**Comment by andreasnoack** [comment]
The tests are now run in parallel so I think this one can be closed. The time is mainly spent on compilation and the only way to save that time would be to avoid testing some methods.

**Comment by ViralBShah** [comment]
Yes, I think this is not a linalg specific problem - except that there are lots of tests.
