### ISSUE TITLE
Add Lyapunov / Sylvester solver

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/LinearAlgebra.jl#76]
There is no Lyapunov / Sylvester solver built-in to Julia, for solving

AXB + CXD = F 

This could be fixed by wrapping the LAPack xTRSYL routine.

**Comment by lindahua** [comment]
+1

**Comment by stevengj** [comment]
Seems worthwhile and low-cost.  What would the interface look like?

**Comment by jiahao** [comment]
I'm in favor of just putting in the LAPACK wrapper for now and deferring a higher-level interface to a symbolic rewrite rule in the same vein as JuliaLang/LinearAlgebra.jl#48. Or we could just do the simple thing and define a new `solvesylvester` function.

**Comment by dlfivefifty** [comment]
You could call the function lyap to match matlab

**Comment by lsorber** [comment]
@dlfivefifty lyap also solves Sylvester equations. Imho, maybe lyap tries to do too much and its functionality should be split into smaller pieces in Julia.

**Comment by atisharma** [comment]
Would a wrapper to SLICOT be a suitable response?

**Comment by mschauer** [comment]
As I understood, SLICOT is not really free, http://slicot.org/obtaining-slicot

**Comment by atisharma** [comment]
SLICOT 4.5 is GPL v3.0. SLICOT 5.0 does indeed look non-free from their website. But strangely it is available in the Debian main repo, and Debian are pretty strict about licencing.

Writing good Lyapunov / Riccati solvers is not that easy and if the SLICOT licence is acceptable it would be preferable to a reimplementation. Perhaps using SLICOT 4.5?

https://github.com/jcrist/Slicot.jl is attempting to create a Julia SLICOT wrapper.

**Comment by mschauer** [comment]
Ah, tricky. Could be that they had 5.0 for a limited time on the website under GPL and then removed the link, so _that_ version 5.0 would be free as well, http://www.dynare.org/pipermail/dev/2011-July/001230.html .

**Comment by johnmyleswhite** [comment]
I think we'd generally try to avoid pulling something GPL3 into Base. Seems better suited for a package.

**Comment by dlfivefifty** [comment]
I've implemented my own lyap in Julia for the time being.  If anyone is interested you can find it as part of ApproxFun:

https://github.com/dlfivefifty/ApproxFun/blob/master/src/PDE/lyap.jl

**Comment by mschauer** [comment]
@dlfivefifty Cool, thank you for implementing it. I would like to use your implementation for the time. Could you put your lyap.jl public domain or under a licence?

**Comment by dlfivefifty** [comment]
As far as I'm concerned it's public domain, but if you require an official license I'm happy to give it to you

**Comment by mschauer** [comment]
Ok, cool. I also have a look at the xTRSYL

**Comment by mschauer** [comment]
I gave it a try, if somebody familiar with Julia-LAPACK interaction could have a look, that would be nice, https://gist.github.com/mschauer/e967a2f1e7dc745c23e7 including naive implementation for comparison.
With some guidance I can make a pull request, or somebody else takes over.

**Comment by ViralBShah** [comment]
You should definitely make a PR, add tests and docs.

**Comment by dlfivefifty** [comment]
```
Looking forward to changing my code to use this!  I didn’t see a wrapper for solving

    AXB^t + CXD^t = F
```

Is a routine for solving this generalized Sylvester equation included in LAPack?  Is it easy to access via your code?

Cheers,

Sheehan

**Comment by mschauer** [comment]
I think there is only Generalized coupled Sylvester in LAPACK, but one can add a wrapper for that as well

```
DTGSYL solves the generalized Sylvester equation
              A * R - L * B = scale * C                 
              D * R - L * E = scale * F
  where R and L are unknown m-by-n matrices
```

**Comment by dlfivefifty** [comment]
Interesting, Mathematica has a LyapunovSolve that does AXB+CXD=F.  I'd be surprised if Wolfram bothered to implement it themselves, so I wonder what they use

**Comment by andreasnoack** [comment]
MATLAB uses [SLICOT](http://slicot.org) but we cannot do that because of the license.

**Comment by tkelman** [comment]
There is a slicot wrapper under-development at https://github.com/jcrist/slicot.jl, it may not have all of the functions exposed yet though.

**Comment by JeffBezanson** [comment]
implemented by JuliaLang/julia#7435

**Comment by atisharma** [comment]
It seems the SLICOT library is dual licence. It will be forked if the licence of future versions is closed. The current version is in the Debian repo, and it seems that there is a commitment to maintain the fork. So perhaps it would be possible to implement as a package?
See https://lists.debian.org/debian-science/2012/06/msg00154.html for the copyright status of the library, and https://lists.debian.org/debian-science/2012/06/msg00154.html for the debian mailing list thread.

**Comment by mschauer** [comment]
Should we reopen? We also still need the discrete time Lyapunov equation

```
A X A' - X + Q = 0 
```

**Comment by tkelman** [comment]
@mschauer I could absolutely use that (also algebraic Riccati if someone wants to be awesome), but if the functionality isn't easily doable via lapack wrappers that would already be in openblas then probably best as a package.

**Comment by mschauer** [comment]
I fear you are right. Maybe we can ping each other if something starts moving.

**Comment by mschauer** [comment]
Perhaps not the canonical way, but https://github.com/mschauer/IDRsSolver.jl solves Stein/discrete Lyapunov equation and other linear equations.

**Comment by zouhairm** [comment]
+1 for discrete time Lyapunov equation and algebraic Riccati...
FWIW, the QuantEcon package https://github.com/QuantEcon/QuantEcon.jl  implements `solve_discrete_lyapunov`.
