### ISSUE TITLE
minor bugs in cholmod.jl

### ISSUE THREAD

**Issue by joachimdahl** [JuliaLang/LinearAlgebra.jl#78]
I noticed what may be a bug in cholmod.jl with chm_spzeros and chm_speye (assuming it's viable to call them):
julia> CHOLMOD.chm_eye(3)

CHOLMOD dense:   :  3-by-3, 
  leading dimension 3, nzmax 9, real, double
  col 0:
         0: 1
         1: 0
         2: 0
  col 1:
         0: 0
         1: 1
         2: 0
  col 2:
         0: 0
         1: 0
         2: 1
  OK

julia> CHOLMOD.chm_speye(3)
ERROR: type: instantiate_type: expected TypeConstructor, got Function
 in chm_speye at linalg/cholmod.jl:897

Another minor issue is in the call to cholmod_factorize_p.  The prototype for cholmod_l_factorize_p is:

int cholmod_l_factorize_p (cholmod_sparse *, double *, SuiteSparse_long *, size_t, cholmod_factor *, cholmod_common *) ;

but in cholmod.jl, it is called as:

```
    function cholfact{Tv<:CHMVTypes}(A::CholmodSparse{Tv,$Ti},beta::Tv,ll::Bool)
        cm = cmn($Ti)
        ## may need to change final_asis as well as final_ll
        if ll cm[chm_final_ll_inds] = reinterpret(Uint8, [one(Cint)]) end
        Lpt = ccall((@chm_nm "analyze" $Ti
                     ,:libcholmod), Ptr{c_CholmodFactor{Tv,$Ti}},
                    (Ptr{c_CholmodSparse{Tv,$Ti}}, Ptr{Uint8}), &A.c, cm)
        @isok ccall((@chm_nm "factorize_p" $Ti
                        ,:libcholmod), Cint,
                       (Ptr{c_CholmodSparse{Tv,$Ti}}, Ptr{Tv}, Ptr{Cint}, Csize_t,
                        Ptr{c_CholmodFactor{Tv,$Ti}}, Ptr{Uint8}),
                       &A.c, &beta, C_NULL, zero(Csize_t), Lpt, cmn($Ti))
        CholmodFactor(Lpt)
    end
```

Probably the Ptr{Cint} type should be a Ptr{$Ti} type instead,  or perhaps it doesn't matter for the C_NULL value?

**Comment by ViralBShah** [comment]
The examples above do not crash any more. The `Ptr{Cint}` is correct, since we are not calling the `_l_factorize_p` method, and it is `C_NULL` anyways.
