### ISSUE TITLE
32-bit julia test failures

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/LinearAlgebra.jl#79]
On my dual-core 32-bit ubuntu test machine, the tests fail to start.

``` julia
~/julia$ make test
    JULIA test/all
```

Setting it to single core, the linalg1 test fails:

``` julia
~/julia$ make test
    JULIA test/all
     * linalg1
exception on 1: ERROR: assertion failed: |:(det(capd)) - :(det(apd))| <= 0.002384185791015625
  :(det(capd)) = 1.626428240984628e9
  :(det(apd)) = 1.6264282410016303e9
  difference = 0.017002344131469727 > 0.002384185791015625
 in error at error.jl:22
 in test_approx_eq at test.jl:68
 in anonymous at no file:54
 in runtests at /home/jameson/julia/test/testdefs.jl:5
 in anonymous at multi.jl:629
 in run_work_thunk at multi.jl:590
 in remotecall_fetch at multi.jl:663
 in remotecall_fetch at multi.jl:678
 in anonymous at task.jl:1320
while loading linalg1.jl, in expression starting on line 23
ERROR: assertion failed: |:(det(capd)) - :(det(apd))| <= 0.002384185791015625
  :(det(capd)) = 1.626428240984628e9
  :(det(apd)) = 1.6264282410016303e9
  difference = 0.017002344131469727 > 0.002384185791015625
 in error at error.jl:22
 in test_approx_eq at test.jl:68
 in anonymous at no file:54
 in runtests at /home/jameson/julia/test/testdefs.jl:5
 in anonymous at multi.jl:629
 in run_work_thunk at multi.jl:590
 in remotecall_fetch at multi.jl:663
 in remotecall_fetch at multi.jl:678
 in anonymous at task.jl:1320
while loading linalg1.jl, in expression starting on line 23
while loading /home/jameson/julia/test/runtests.jl, in expression starting on line 32
```

(p.s. is this linalg1 test supposed to take several hundred megabytes of RAM? I've only assigned my VM 1GB)

**Comment by jiahao** [comment]
Duplicate of JuliaLang/LinearAlgebra.jl#69. For now, it will be ok to manually adjust the magic constant to make it pass (ref: JuliaLang/LinearAlgebra.jl#67.)

**Comment by jiahao** [comment]
Rather, it is not an exact duplicate, but the same test is failing.

**Comment by mschauer** [comment]
JuliaLang/julia#5743 reduces the risk of this type of error and fixes this as a side effect, if I remember correctly. (If you run enough tests with different combinations of enough element types, and generate a new random integer matrix for every of these combinations, at one point you will end up testing over a singular matrix).

**Comment by staticfloat** [comment]
Is this still an issue?

**Comment by tkelman** [comment]
I believe these tolerance issues in the linalg tests have been fixed. It was briefly possible to build a 32-bit copy of Julia on 64-bit Linux which made these things a little easier to check, but Keno broke that a month or two ago with some of his libcxxabi changes to `Make.inc`.

**Comment by andreasnoack** [comment]
I guess this one is not an issue anymore.

**Comment by ViralBShah** [comment]
I don't recollect seeing this fixed. I will try it on my 32-bit image, and will reopen if necessary.

**Comment by ViralBShah** [comment]
I compiled julia on a 32-bit ubuntu 12.04 image, and find that it passes all the linalg tests.

**Comment by ViralBShah** [comment]
I see these warnings. Anyone know what they are?

```
     * broadcast
     * complex
     * socket
     * floatapprox
     * readdlm
     * reflection
The following 'Returned code...' warnings indicate normal behavior:
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
```

**Comment by tkelman** [comment]
JuliaLang/julia#9521 JuliaLang/julia#9571
