### ISSUE TITLE
row-vector/column-vector products should act like dot products

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/LinearAlgebra.jl#8]
If `x` and `y` are vectors of the same length, then `(x*x')*y` works but `x*(x'*y)` does not (it gives `ERROR: no method *(Array{Float64,1},Array{Float64,1})`).  The latter can only be accomplished with `x*dot(x,y)`.

This is surprising and, I think, undesirable: `*` should be associative (neglecting floating-point roundoff errors, of course).

Another way of putting it is that `x'*y`, or any product of a row vector and a column vector, should return a scalar, not a vector of length 1.  (And it should probably just call the BLAS `dot`.)

**Comment by andreasnoack** [comment]
This has been discussed a few times, I think. At least in JuliaLang/julia#2472. Actually `x'*y` for vectors `x` and `y` already calls `dot` but wraps it in a vector afterwards.

**Comment by stevengj** [comment]
At the very least, a column-vector of length 1 should act like a 1&times;1 matrix for multiplication purposes.   e.g. `x * [2]` should work and be equivalent to `2x`.

**Comment by toivoh** [comment]
I think that it might make sense to demote a length one vector to a scalar
in cases where a vector does not make sense. We know that dimensions can be
added spuriosly (typically by transposition).

**Comment by p-zubieta** [comment]
This works now, right?

**Comment by StefanKarpinski** [comment]
Yes:

```jl
julia> x = rand(3)
3-element Array{Float64,1}:
 0.61878
 0.178213
 0.0933086

julia> y = rand(3)
3-element Array{Float64,1}:
 0.954149
 0.0926293
 0.336523

julia> (x*x')*y
3-element Array{Float64,1}:
 0.394978
 0.113756
 0.0595605

julia> x*(x'*y)
3-element Array{Float64,1}:
 0.394978
 0.113756
 0.0595605
```
