### ISSUE TITLE
Balancing not a problem in LAPACK 3.5

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/LinearAlgebra.jl#80]
When we upgrade to next version of OpenBLAS, we are also upgrading to LAPACK 3.5 in which the balancing functions `xgebal` have been changed. This will cause a test error because the nasty test matrix we are using now to test the effect of balancing is not nasty enough anymore. If possible we'll have to come up with a new nasty matrix.

I don't have time to look into it now so this issue is just a reminder of the problem and why the linalg tests will fail when we upgrade.

Reference: http://arxiv.org/pdf/1401.5766v1.pdf

**Comment by andreasnoack** [comment]
As noted in JuliaLang/julia#5965 this already affects the Windows builds because they use OpenBLAS 2.9rc1.

I have tried to construct a matrix that gives wrong eigenvectors when balancing it the LAPACK 3.5 way, but I haven't succeeded.

**Comment by tkelman** [comment]
Yes, even the 0.3 prerelease Windows binaries are currently failing this test.

**Comment by jiahao** [comment]
Cross-ref: JuliaLang/LinearAlgebra.jl#50, JuliaLang/julia#7213

**Comment by andreasnoack** [comment]
Maybe we could turn around the test case. Since it is now impossible to choose a matrix for which balancing destroys the eigen calculation we choose a matrix that is poorly handled without balancing and check that instead.

**Comment by jiahao** [comment]
Yes, that is probably easier.

**Comment by andreasnoack** [comment]
The code path is tested so I'm closing.
