### ISSUE TITLE
gsvd = svd(A,B) documentation advertises a QR not performed

### ISSUE THREAD

**Issue by alanedelman** [JuliaLang/LinearAlgebra.jl#83]
The doc says

Base.svd(A, B) -> U, V, Q, D1, D2, R0

   Compute the generalized SVD of "A" and "B", returning "U",
   "V", "Q", "D1", "D2", and "R0" such that "A =
   U_D1_R0_Q'" and "B = V_D2_R0_Q'".

but only five outputs are returned -- essentialy R0 and Q are replaced
with X=Q \* R0  which is fine if the doc is consistent

**Comment by andreasnoack** [comment]
The QR is actually done and saved in the object when you do a `svdfact`, but in `svd` it is undone for consistency with MATLAB's `gsvd`. Do you prefer returning `Q` and `R0` or changing the documentation?

**Comment by alanedelman** [comment]
I actually kind of like the idea it's done
maybe best if the doc for svd explained the correct calling sequence and mentioned svdfact

**Comment by andreasnoack** [comment]
Fixed by JuliaLang/julia#5941
