### ISSUE TITLE
Bad type inference for eig

### ISSUE THREAD

**Issue by simonster** [JuliaLang/LinearAlgebra.jl#87]
The relevant code is:

``` julia
function eig(A::Union(Number, AbstractMatrix); kwargs...)
    F = eigfact(A, kwargs...)
    F[:values], F[:vectors]
end
```

I don't know this code well enough to know if the best way to solve this is using typeasserts or by accessing the fields directly instead of calling `getindex`.

**Comment by jiahao** [comment]
I'm not sure what the issue is. Most of the work is done in eigfact! anyway.

**Comment by simonster** [comment]
`F[:values]` and `F[:vectors]` are calls to [`getindex(A::Union(Eigen,GeneralizedEigen), d::Symbol)`](https://github.com/JuliaLang/julia/blob/62be2c69cd6a8cb404ea8d63d37bd5b8d1df5d3f/base/linalg/factorization.jl#L631), which is type unstable because `F.values` and `F.vectors` have different types. But I'm not entirely clear what the rationale behind that `getindex` method is in the first place.

**Comment by jiahao** [comment]
This is a function designed for Matlab compatibility. The native Julia code is actually in eigfact (which calls eigfact!).

**Comment by andreasnoack** [comment]
All the `Factorization`s have `getindex` methods and the idea is that most often the user shouldn't think about the internal representation of the factorization. This is not so obvious for `Eigen`, but more so for `LU` or `QRCompactWY`. For `LU` your can get the permutation vector by writing `F[:p]`, but that vector is not stored in the object, it is constructed in `getindex`. In `QRCompactWY` the triangular `R` part is stored together with information about the elementary reflectors so you can't extract `R` from a field in the factorization. For `Eigen` the output of `geindex` is just the fields, but I think it is a good idea that users generally shouldn't touch the fields.

I think that type instability `getindex` is not so unusual. If the result from the eigencalculation was stored in a tuple or `Any` array then the `getindex` methods would also be type unstable.

**Comment by JeffBezanson** [comment]
See also JuliaLang/LinearAlgebra.jl#12, JuliaLang/LinearAlgebra.jl#1512, JuliaLang/LinearAlgebra.jl#21
