### ISSUE TITLE
gemv speed regression on Windows on nightly

### ISSUE THREAD

**Issue by jaakkor2** [JuliaLang/LinearAlgebra.jl#880]
```
using LinearAlgebra, BenchmarkTools
n,m=1000,100; A=rand(n,m); x=rand(m); y=A*x; @btime mul!(y,A,x);
```
On nightly, the performance is 50% slower than on 1.6 or 1.7. Using Windows 10, i7-10750H, I get 
```
54.300 μs (0 allocations: 0 bytes) # Version 1.8.0-DEV.709
52.500 μs (0 allocations: 0 bytes) # Version 1.8.0-DEV.761
35.200 μs (0 allocations: 0 bytes) # Version 1.6.3
35.600 μs (0 allocations: 0 bytes) # Version 1.7.0-rc1
```
The performance was already really bad compared to running the Linux binary under WSL2 on the same machine
```
4.100 μs (0 allocations: 0 bytes) # Version 1.8.0-DEV.761
5.667 μs (0 allocations: 0 bytes) # Version 1.7.0-rc1
```
All tested binaries are from https://julialang.org/downloads/ .

**Comment by ViralBShah** [comment]
How many cores do you have and what does `BLAS.get_num_threads()` give? Can you try the nightlies tomorrow or day after? I just merged an openblas update, but it is likely that this is because it is saturating the number of threads based on the number of hyperthreads available. Can you set the number of blas threads the same as number of cores and see what you get?

**Comment by jaakkor2** [comment]
Running  `Version 1.8.0-DEV.781 (2021-10-19)  refs/pull/42708/merge/a65412e75b (fork: 4 commits, 0 days)` from `https://julialangnightlies-s3.julialang.org/assert_pretesting/winnt/x64/1.8/julia-a65412e75b-win64.exe`  (this is build from https://github.com/JuliaLang/julia/pull/42708 ) gives 

`BLAS.get_num_threads()` = 12 as default

```
for n in [1,2,4,6,8,10,12]
    BLAS.set_num_threads(n)
    @btime mul!(y,A,x);
end
```
gives
```
11.900 μs (0 allocations: 0 bytes)
16.600 μs (0 allocations: 0 bytes)
19.900 μs (0 allocations: 0 bytes)
25.400 μs (0 allocations: 0 bytes)
35.100 μs (0 allocations: 0 bytes)
43.500 μs (0 allocations: 0 bytes)
52.000 μs (0 allocations: 0 bytes)
```
` Threads.nthreads()` = 12.

https://ark.intel.com/content/www/us/en/ark/products/201897/intel-core-i710850h-processor-12m-cache-up-to-5-10-ghz.html says i7-10850H total cores =  6, total threads = 12.

Same for `using MKL` gives
```
10.500 μs (0 allocations: 0 bytes)
7.120 μs (0 allocations: 0 bytes) 
3.450 μs (0 allocations: 0 bytes) 
2.962 μs (0 allocations: 0 bytes) 
2.789 μs (0 allocations: 0 bytes) 
3.011 μs (0 allocations: 0 bytes) 
2.800 μs (0 allocations: 0 bytes) 
```

**Comment by ViralBShah** [comment]
There are two things here. One is that we should set the number of threads based on physical cores.

In addition, there appears to be a windows issue in how we build openblas (or perhaps in openblas itself). @staticfloat @DilumAluthge @giordano may be the right folks to ping.

**Comment by ViralBShah** [comment]
Is this performance regression also present in other linear algebra routines?

**Comment by jaakkor2** [comment]
gemm seems to perform fine
`peakflops(8000)`
```
5.3761962056245735e10 # 1.6.3 , this is https://github.com/JuliaLang/julia/issues/40497 due to OpenBLAS 0.3.10
2.2184438868341443e11 # 1.7.1rc1
2.734984514352085e11 # a65412e75b (from JuliaLang/julia#42708)
```
`using MKL` gives 235..254 GFlops.

**Comment by staticfloat** [comment]
Well, I've been able to identify that this is in fact due to OpenBLAS and not anything else.  On my Windows VM, I can see a slowdown when directly `ccall()'ing` `dgemv_64_`.  Here's my test suite (which also bypasses LBT to ensure that that's not the source of the difference:

```
using Libdl, LinearAlgebra, BenchmarkTools
n,m=1000,100
A=rand(n,m)
x=rand(m)
y=A*x

libopenblas = Libdl.dlopen(only(filter(l -> occursin("libopenblas64_", l), Libdl.dllist())))
dgemv = Libdl.dlsym(libopenblas, "dgemv_64_")
@btime ccall(dgemv, Cvoid, (Ref{UInt8}, Ref{Int64}, Ref{Int64}, Ref{Float64}, Ptr{Float64}, Ref{Int64}, Ptr{Float64}, Ref{Int64}, Ref{Float64}, Ptr{Float64}, Ref{Int64}, Clong), 'N', size(A,1), size(A,2), 1.0, A, 1000, pointer(x, 1), 1, 0.0, pointer(y, 1), 1, 1)
```

Getting the OpenBLAS config, there's a lot of space for changes here, as my two test setups return the following:
```
# Slow julia
julia> unsafe_string(ccall(Libdl.dlsym(libopenblas, "openblas_get_config64_"), Cstring, ()))
"OpenBLAS 0.3.17  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=512" 
```

```
# Fast julia
julia> unsafe_string(ccall(Libdl.dlsym(libopenblas, "openblas_get_config64_"), Cstring, ()))
"OpenBLAS 0.3.10  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=32"
```

So my guesses right now are that this is either a regression somewhere from OpenBLAS `0.3.10` -> `0.3.17`, or it's a consequence of `MAX_THREADS` going from `32` -> `512`.

**Comment by giordano** [comment]
> or it's a consequence of MAX_THREADS going from 32 -> 512.

You could do a 0.3.17 build with 32 threads to rule this out (or confirm it)?

**Comment by jaakkor2** [comment]
All these numbers are on Windows, and performance consistently looks like the number of threads is 8.
In the first post above, on Julia nightly, the number of threads is 12 causing the regression.

Seems like the slow performance on Windows is really due to OpenBLAS.

Julia 1.5.4
38.000 μs (9 allocations: 144 bytes)
"OpenBLAS 0.3.9  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott MAX_THREADS=32"

Julia 1.6.4
36.800 μs (9 allocations: 144 bytes)
"OpenBLAS 0.3.10  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott MAX_THREADS=4096"

Julia 1.7.0
38.900 μs (9 allocations: 144 bytes)
"OpenBLAS 0.3.13  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=4096"

Then the version from Conda
`C:\Users\jaakkor2\.julia\conda\3\Library\bin\openblas.dll`
 37.600 μs (9 allocations: 144 bytes)
"OpenBLAS 0.3.18 DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=128"

And with the official asset from https://github.com/xianyi/OpenBLAS/releases/download/v0.3.18/OpenBLAS-0.3.18-x64.zip
38.900 μs (9 allocations: 144 bytes)
"OpenBLAS 0.3.18 DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64"

In the two last cases, `dgemv_64_`->`dgemv_` and `openblas_get_config64_`->`openblas_get_config`.

**Comment by jaakkor2** [comment]
On my machine with Intel i7-107850H (6 cores) on Windows on Julia 1.8.0-rc1, `LinearAlgebra.BLAS.get_num_threads()`  gives 6, whereas Julia 1.7.3 gives 8.

`using BenchmarkTools, LinearAlgebra; n,m=1000,100;A=rand(n,m); x=rand(m);y=A*x; @btime mul!(y,A,x);`

gives
* 1.8.0-rc1: 24.900 μs (0 allocations: 0 bytes)
* 1.7.3:  35.200 μs (0 allocations: 0 bytes)

The regression is now gone due to number of threads setting.  Still GEMV is 10x slower than MKL, but that is not the issue here.
