### ISSUE TITLE
multiple issues with binary operators applied to arguments of mixed precision

### ISSUE THREAD

**Issue by bsxfan** [JuliaLang/LinearAlgebra.jl#9]
@JeffBezanson and @ViralBShah , I'm creating this issue to subsume issues JuliaLang/julia#2853 and JuliaLang/julia#2933, in the hope that they can be addressed together with a single solution.
- JuliaLang/julia#2853 was closed with a commit that introduced a bug, see details below
- JuliaLang/julia#2933 was closed without being resolved, in order to include it in this issue

The general problem is that operations like matrix-matrix or matrix-vector multiplication are fast when dispatched to BLAS, but this can only be done if the arguments are of the same precision. Otherwise Julia defaults to slower implementations. Converting (and therefore unfortunately copying) one of the arguments to make the types agree and then sending to BLAS can be much faster.

In a solution, I propose that the following be addressed:
- [ ] Include  operators *, \ and /
- [ ] consider matrix and vector arguments
- [ ] consider mixtures of precisions (32 vs 64 bits) and maybe also Integer and Rational
- [ ] consider mixtrures of real and complex types
- [ ] consider the interaction of multiplication and transposition

Although issue  JuliaLang/julia#2853 was addressed via commit https://github.com/JuliaLang/julia/commit/4b7ef605cf0e4ba852b76d9b1f0775e3319013a2, the following problems remain:
- [x] New bug: The solution fails to cater for P = A*X where A::StridedMatrix{Float64} and X::StridedVector{Complex64}. It crashes with InexactError(), because it is trying to convert from single-precision complex to double-precision real.
- [x] For matrix A and vector v, the element type of P = A*v depends only on the element type of A. I think it should depend on both. This is what causes the above crash and it also causes perhaps unexpected behaviour: Elsewhere in Julia, one finds for example:
  
  `promote_type(Float32,Float64) == promote_type(Float64,Float64) == Float64`

while in the case of P = A*v, v will be downcast (not promoted) to 32-bit precision if A is of 32-bit precision.
- [ ] matrix-matrix multiplication and the operators \ and / have not been addressed.

**Comment by ViralBShah** [comment]
Cc: @andreasnoackjensen

**Comment by jiahao** [comment]
> The general problem is that operations like matrix-matrix or matrix-vector multiplication are fast when dispatched to BLAS, but this can only be done if the arguments are of the same precision.

This is no longer strictly true in newer BLASes, which may have the mixed-precision routines described in [LAWNS JuliaLang/julia#149](http://www.netlib.org/lapack/lawnspdf/lawn149.pdf). (XBLAS?) The list of symbols in OpenBLAS [suggests](https://github.com/xianyi/OpenBLAS/blob/0f6e79f918d930ce766c9f2d424204b397cb7314/exports/gensymbol#L221) that they exist there, but I can't figure out what they are called.

There are also the mixed-precision LAPACK routines like [dsgesv](https://github.com/xianyi/OpenBLAS/blob/c5437149c0e538950f8df79edc9a795465a709fa/lapack-netlib/SRC/dsgesv.f) and [zcgesv](https://github.com/xianyi/OpenBLAS/blob/c5437149c0e538950f8df79edc9a795465a709fa/lapack-netlib/SRC/zcgesv.f) that could be wrapped for mixed precision routines.

**Comment by andreasnoack** [comment]
I don't think there is much else to do here. Now we promote to common element type for multiplication and solve and we reinterpret complex arrays to real when possible.
