### ISSUE TITLE
sprand(1,1,_) doesn't work

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/LinearAlgebra.jl#92]
``` julia
julia> sprand(1,1,1.0)
ERROR: InexactError()
 in sprand at sparse/sparsematrix.jl:367
 in sprand at sparse/sparsematrix.jl:407
```

(This happens for just about every value of the density parameter I've tried.)

**Comment by jiahao** [comment]
Along a similar vein, `sprand(0,0,_)` throws a `DomainError` whereas I would have expected it to behave like `spzeros(0,0)`.

**Comment by andreasnoack** [comment]
How did you find out? 1x1 is not the most obvious size for a sparse matrix. At least not in econometrics.

**Comment by jiahao** [comment]
I was bored.
