### ISSUE TITLE
What happened to svds?

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/LinearAlgebra.jl#95]
The documentation describes a [`svds`](http://julia.readthedocs.org/en/latest/stdlib/linalg/#Base.svds) function, but as far as I can tell this function doesn't exist. The closest thing I've found is Issue JuliaLang/LinearAlgebra.jl#28.

Did we ever have a sparse svd function?

**Comment by ViralBShah** [comment]
We used to but it never worked well. I thought I removed it from the docs too.

**Comment by ViralBShah** [comment]
Implementation of `svds` is discussed in JuliaLang/LinearAlgebra.jl#106
