### ISSUE TITLE
axpby! exported twice

### ISSUE THREAD

**Issue by ctkelley** [JuliaLang/LinearAlgebra.jl#954]
Running CI on a package for 1.9-DEV. Seems that BLAS and LAPACK have
a conflict. Macbook M2 Air running latest OS.

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0-DEV.1396 (2022-09-18)
 _/ |\__'_|_|_|\__'_|  |  Commit f794bdd98b3 (0 days old master)
|__/                   |

julia> using LinearAlgebra

julia> using LinearAlgebra.BLAS

julia> using LinearAlgebra.LAPACK

julia> axpby!()
WARNING: both BLAS and LinearAlgebra export "axpby!"; uses of it in module Main must be qualified
ERROR: UndefVarError: axpby! not defined
Stacktrace:
 [1] top-level scope
   @ REPL[4]:1
```

**Comment by inkydragon** [comment]
`LinearAlgebra.BLAS` wraps the interface to the low level BLAS library via ccall.
`LinearAlgebra` is based on `LinearAlgebra.BLAS` and exporte more functions.
Therefore some functions are duplicated.

In fact `LinearAlgebra.BLAS.axpby!` and `LinearAlgebra.axpby!` are the same function.
Conflicts can be avoided by keeping the BLAS prefix.

**Comment by ctkelley** [comment]
I'm confused. I have not seen this error before and have been putting
```
using LinearAlgebra
using LinearAlgebra.BLAS
using LinearAlgebra.LAPACK
```
in modules for years with no problems. Why is the problem happening now?

This is new. So if the functions have been duplicated forever, then warning or error are new.

**Comment by ctkelley** [comment]
The  problem is also there on Intel MACs with v1.9. 
```
Commit 6cd2a9df645 (20 days old master)
```
All is fine with 1.8.1

**Comment by fredrikekre** [comment]
> In fact LinearAlgebra.BLAS.axpby! and LinearAlgebra.axpby! are the same function.

I believe you meant they are *not* the same function. This is intentional (#44758) but it is unfortunate that it gives this name collision.

**Comment by ctkelley** [comment]
Seems that [#44758](https://github.com/JuliaLang/julia/pull/44758) was pushed before 1.8.0 was released, so why am I getting the problem only with 1.9? Shouldn't this have also been trouble with 1.8?

**Comment by ctkelley** [comment]
My package is passing CI with github actions for the nightly build. I get the problem only when I run CI locally. Any ideas why that should be the case?

**Comment by giordano** [comment]
> Seems that JuliaLang/julia#44758 was pushed before 1.8.0 was released, so why am I getting the problem only with 1.9?

Version 1.8 was branched out in February: https://github.com/JuliaLang/julia/pull/44203

> Shouldn't this have also been trouble with 1.8?

No.

**Comment by ctkelley** [comment]
OK. This change will break a lot of things, not just for me.

**Comment by N5N3** [comment]
The best solution seems to be not export them from `BLAS` (just like `BLAS.dot`)
