### ISSUE TITLE
Occasional test suite failure due to ARPACK 

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/LinearAlgebra.jl#96]
I think this was caused by JuliaLang/julia#6053. It's not obviously wrong, but I suspect that ARPACK sometimes has trouble converging.

``` julia
ERROR: assertion failed: |apd * v[:,3] - d[3] * v[:,3]| <= 0.0029802322387695312
  apd * v[:,3] = -.019031286
.46720278
-.07452887
-.3921632
.09536207
.20611131
-.05333458
-.32105684
.16663378
.45608377

  d[3] * v[:,3] = -.019333333
.4655577
-.07656061
-.3949156
.0916988
.20555612
-.0542634
-.32141235
.16885556
.45497692

  difference = 0.0036632642 > 0.0029802322387695312
 in anonymous at task.jl:1311
while loading arpack.jl, in expression starting on line 1
```

**Comment by jiahao** [comment]
Has anyone seen this recently?

**Comment by ViralBShah** [comment]
No, but a lot of stuff has been fixed in our arpack stuff since, so I am keen to close it unless it reappears.

**Comment by ViralBShah** [comment]
Cc: @Jutho 

We have run tests repeatedly scores of times on master recently, with no failures - so I am keen to just close this for now.

**Comment by staticfloat** [comment]
Agreed, things are even passing on 32-bit!
