### ISSUE TITLE
Make arithmetic ops on sparse matrices return sparse matrices

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaLang/LinearAlgebra.jl#98]
At the moment, several functions on sparse matrices return dense matrices, when sparse matrices could (and probably should) be returned instead.

A list of these functions minimally includes:
- iceil
- ceil
- ifloor
- floor
- abs
- abs2

Any scalar function that always returns 0 when given 0 as an input could be included in this list, although a few like `sin` probably should not be added to the list.

**Comment by jiahao** [comment]
I haven't given this much thought, but should elements that map to zeros be stored zeros or removed entirely from the list? What's the performance tradeoff?

**Comment by johnmyleswhite** [comment]
I'd think it would be simpler to map them to zeros so that `nfilled` for the output is predictable.

**Comment by tkelman** [comment]
Makes sense to me to just apply the operation to the `nzval` vector, for operations that map zero to zero. Especially now that explicit zeros are allowed - `ceil(-0.5*speye(2))` would just have explicit zeros along the diagonal.

Maybe worth adding an explicit `packnz` and/or `packnz!` function to prune out stored zeros?

**Comment by ViralBShah** [comment]
Anything that maps a 0 to a 0 should certainly yield a sparse result. I generally do not like leaving stored zeros around except inside library codes. Extra cost of the zero check should not be much.

**Comment by tkelman** [comment]
It's not the zero check that's expensive, it's the rearrangement and copying of all the remaining nonzero indices you need to do to remove a stored zero. But since `A.nzval = ceil(A.nzval)` is easy enough to do if you know what you're doing, the default behavior could certainly be to remove stored zeros despite the performance difference.

**Comment by ViralBShah** [comment]
The way to implement it is that you just keep an extra counter and copy the nonzero results as you stream through the input, without any rearrangement or copying. That's how the sparse libraries are implemented.

**Comment by tkelman** [comment]
So, something like this then?

```
## Unary operators that map 0 to 0

for (op, restype) in ( (:iceil, Integer), (:ceil, Nothing), (:ifloor, Integer),
                       (:floor, Nothing), (:abs, Real), (:abs2, Real) )
    @eval begin

        function ($op){Tv,Ti}(A::SparseMatrixCSC{Tv,Ti})
            nfilledA = nfilled(A)
            colptrB = Array(Ti, A.n+1)
            rowvalB = Array(Ti, nfilledA)
            nzvalB = Array($(restype==Nothing ? (:Tv) : restype), nfilledA)

            k = 0 # number of additional zeros introduced by op(A)
            for i = 1 : A.n
                colptrB[i] = A.colptr[i] - k
                for j = A.colptr[i] : A.colptr[i+1]-1
                    opAj = $(op)(A.nzval[j])
                    if opAj == 0
                        k += 1
                    else
                        rowvalB[j - k] = A.rowval[j]
                        nzvalB[j - k] = opAj
                    end
                end
            end
            colptrB[end] = A.colptr[end] - k
            deleteat!(rowvalB, colptrB[end]:nfilledA)
            deleteat!(nzvalB, colptrB[end]:nfilledA)
            return SparseMatrixCSC(A.m, A.n, colptrB, rowvalB, nzvalB)
        end

    end # quote
end # macro
```

Actually `abs` and `abs2` should probably be handled separately, since there you're not worried about introducing extra nonzeros as much as you are outputting a different type than the input.

**Comment by ViralBShah** [comment]
Yup, this is the way to do it. Do you observe any major performance differences?

**Comment by tkelman** [comment]
Sorry I fail at timing. It's about the same, or even better to allocate less memory.

```
julia> A = sprandn(5000,5000,0.5);
julia> @time begin B=copy(A); B.nzval = ceil(B.nzval); end;
elapsed time: 0.38222586 seconds (300296916 bytes allocated)
julia> @time begin B=copy(A); B.nzval = ceil(B.nzval); end;
elapsed time: 0.33151745 seconds (300055184 bytes allocated)
julia> @time begin B=copy(A); B.nzval = ceil(B.nzval); end;
elapsed time: 0.294850493 seconds (300055184 bytes allocated)
julia> @time begin B=copy(A); B.nzval = ceil(B.nzval); end;
elapsed time: 0.374110318 seconds (300055184 bytes allocated)
julia> @time C=ceil(A);
elapsed time: 0.374186778 seconds (201225912 bytes allocated)
julia> @time C=ceil(A);
elapsed time: 0.301121756 seconds (200050176 bytes allocated)
julia> @time C=ceil(A);
elapsed time: 0.319896548 seconds (200050176 bytes allocated)
julia> @time C=ceil(A);
elapsed time: 0.320185967 seconds (200050176 bytes allocated)
julia> B==C
true
julia> nfilled(A)
12500620
julia> nfilled(B)
12500620
julia> nfilled(C)
8231747
```

Interestingly for `abs` it's about 4x slower to do the zero check, but that may be because I don't have the types right.

**Comment by ViralBShah** [comment]
More interestingly, we ignore sign bit (by definition) in unary minus on sparse matrices. :-)

```
julia> signbit((-speye(10,10))[1,2])
0
```

**Comment by ViralBShah** [comment]
@johnmyleswhite I was thinking about adding `sin` to this list too. Any reason why not?

**Comment by johnmyleswhite** [comment]
I didn't put `sin` on my list since I thought it would break symmetry with `cos`, which will always return a dense matrix.

**Comment by tkelman** [comment]
also note:

```
A = sparse(1:2, 1:2, [1.0:2.0] .+ [1:2]im)
eltype(abs2(full(A))) # Float64
eltype(abs2(A)) # currently Complex{Float64}, but with 0 imaginary part

B = sparse(1:2, 1:2, [1:2] .+ [1:2]im)
eltype(abs(full(B))) # Float64
eltype(abs(B)) # ERROR: InexactError() in abs at sparse/sparsematrix.jl:466
eltype(sin(full(B))) # Union(Complex{Float64},Complex{Int64}) <- is that right?
eltype(sin(B)) # ERROR: InexactError()
```

**Comment by ViralBShah** [comment]
I have to pay attention to complex...

**Comment by ViralBShah** [comment]
@johnmyleswhite I think it is ok to break the symmetry. I have followed the principle of keeping the result sparse if it has the same sparsity or lesser than the input.

**Comment by tkelman** [comment]
Some of the inverse trig functions can skip the zero-check if they don't have roots anywhere in the complex plane other than 0. For anything without a zero-check, maybe the types would be easier to get right if it was just `($op)(A::SparseMatrixCSC) = SparseMatrixCSC(A.m, A.n, A.colptr, A.rowval, ($op)(A.nzval))`? Will the constructor make a copy of the `colptr`, `rowval`, and/or `nzval` vectors?

**Comment by ViralBShah** [comment]
The constructor doesn't makes a copy, IIRC.

**Comment by tkelman** [comment]
Okay so safer to explicitly copy `A.colptr` and `A.rowval` then, and the math operators on the `nzval` vector already have to make a copy.

**Comment by ViralBShah** [comment]
Yes, that's what has to be done.

Also Cc: @tanmaykm
